### ISSUE TITLE
validator should include transaction based on gas used

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#1000]
__Proposal:__ validator should include transactions based on gas used

track issue for the long-term solution of https://github.com/tharsis/ethermint/issues/989.

__Current behavior:__ we have a temporary solution right now

__Desired behavior:__

[PrepareProposal in abci++](https://github.com/tendermint/tendermint/blob/master/spec/abci%2B%2B/abci%2B%2B_methods_002_draft.md#prepareproposal)
We can run the tx in the PrepareProposal phase, and truncate the preliminary transaction list according to the gas used.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by loredanacirstea** [comment]
Related issue: https://github.com/tharsis/evmos/issues/311 (blocks are filled with more transactions than can be processed, due to the block gas limit), as this can still happen now.
