### ISSUE TITLE
Need an api to recover execution result from the false-failed tx

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#1052]
__Proposal:__ Need an api to recover execution result from the false-failed tx

__Current behavior:__

On cronos mainnet, due to an old bug(https://github.com/cosmos/cosmos-sdk/pull/10770), there are transactions that success on chain but return a failed result, although the bug itself is fixed, we need to figure out a way to patch the old data.
One solution is to support sth like: `debug_runTransactionByBlockAndIndex`, so we can rerun these transactions and get back the correct tx result.

__Desired behavior:__ The old tx data should be recovered too.

__Use case:__ Fix the old tx result.

**Comment by fedekunze** [comment]
I think we should modularize the RPC so that projects can add their own namespaces and endpoints to existing namespaced

**Comment by yihuang** [comment]
> I think we should modularize the RPC so that projects can add their own namespaces and endpoints to existing namespaces. This would fix your issue without adding custom endpoints

yeah, maybe add a custom grpc query in cronos is enough, no need to do this in ethermint, we'll try that.

**Comment by zhaojun-sh** [comment]
> On cronos mainnet, due to an old bug([cosmos/cosmos-sdk#10770](https://github.com/cosmos/cosmos-sdk/pull/10770)), there are transactions that success on chain but return a failed result, although the bug itself is fixed, we need to figure out a way to patch the old data.

This type transaction should be correctly identified by Metamask, Explorer, Bridge, etc. It requires compliance with the eth_getTransactionReceipt API. 

`curl --location --request POST 'https://evm-cronos.crypto.org/' --header 'Content-Type: application/json'  --data-raw '{"jsonrpc":"2.0", "method":"eth_getTransactionReceipt", "params":["0xdc77a3531c737bdac89da5184189455a4f542bb1971670909be2e0e6eff6783c"],"id":1}'
`
