### ISSUE TITLE
Consensus failed if you delegate too much: check limit value on voting power

### ISSUE THREAD

**Issue by Microsxema** [tharsis/ethermint#1066]
__Proposal:__ Check limit value on voting power or replace with big int

__Current behavior:__  if I delegated to validator and voting power was more than `1152921504606846975` value then the whole network of 3 validators failed

__Desired behavior:__  check before broadcast transactions or replace int64 with big int

__Use case:__ Is this a vulnerability?

Error:

```
8:45AM ERR failed init node error="error during handshake: error on replay: commit failed for application: error changing validator set: to prevent clipping/overflow, voting power can't be higher than 1152921504606846975, got 1348616000000000001"
```

**Comment by yihuang** [comment]
I think it's a cosmos-sdk thing, If the total supply of staking tokens are too big, the `DefaultPowerReduction` should be increased accordingly, to avoid overflow of voting power in tendermint.
