### ISSUE TITLE
Allow from field to be empty

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#110]
__System info:__ 

MacOs

__Steps to reproduce:__

Some tools such as metamask or truffle does not set the field 'from' when sending a transaction. Instead it expects the value to be extracted from the signature.

( snippet from geth to extract sender address from signature 
https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_signing.go#L131 )

However some antler handler such as the `EthAccountVerificationDecorator` expect the MsgEthereumTx field 'from' to be not empty or it will returns an error.

I suggest either to modify the logic in the AnteHandler to extract the sender address from the signature if it is not in the message or always set the field `from` in the cosmos tx with the signature if it is not present in the eth tx.

What do you think?

linked to issue 

#79

**Comment by fedekunze** [comment]
so the msg validation allows the `From` field to be empty. I recently (#109) changed the `EthSigVerify` ante handler decorator to set up the sender address if not already. What other actionable items do you think are left for this issue?

**Comment by thomas-nguy** [comment]
thanks, I think this fix should solve the issue with empty field `from`. 
(I guess the ValidateBasic verification of the from address become redundant now)

With current main, I am unable to broadcast transaction. Is there any protobuf file to be updated?

**Comment by fedekunze** [comment]
> Is there any protobuf file to be updated?

not to my knowledge. Should we just close this issue @thomas-nguy?

**Comment by thomas-nguy** [comment]
yes this can be closed
