### ISSUE TITLE
`importRawKey` api timed out

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#111]
__System info:__ [ethermint(69f8837c76610adb8588303527d9bc252e0c831b), macosx, python3.8]

__Steps to reproduce:__

1. start local devnet with ethermint
1. Use python web3 library to test
```
>>> web3.geth.personal.importRawKey('5D665FBD2FB40CB8E9849263B04457BA46D5F948972D0FE4C1F19B6B0F243574', '1')
Traceback (most recent call last):
   ...
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=1317): Read timed out. (read timeout=10)
```

**Comment by fedekunze** [comment]
the JSON-RPC endpoint works fine for me

```
curl -X POST --data '{"jsonrpc":"2.0","method":"personal_importRawKey","params":["<priv_key>", "key"],"id":1}' -H "Content-Type: application/json" http://localhost:1317  
```

**Comment by yihuang** [comment]
> the JSON-RPC endpoint works fine for me
> 
> ```
> curl -X POST --data '{"jsonrpc":"2.0","method":"personal_importRawKey","params":["<priv_key>", "key"],"id":1}' -H "Content-Type: application/json" http://localhost:1317  
> ```
> 
> not sure if there's any other underlying issue with the web3 library compatibility

> the JSON-RPC endpoint works fine for me
> 
> ```
> curl -X POST --data '{"jsonrpc":"2.0","method":"personal_importRawKey","params":["<priv_key>", "key"],"id":1}' -H "Content-Type: application/json" http://localhost:1317  
> ```
> 
> not sure if there's any other underlying issue with the web3 library compatibility

Strange, I can reproduce with curl too:
```
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"personal_importRawKey","params":["5D665FBD2FB40CB8E9849263B04457BA46D5F948972D0FE4C1F19B6B0F243574", "1"],"id":1}' http://localhost:1317
```
it hangs.

**Comment by yihuang** [comment]
Ok, the issue is with the keyring backend read user input, and I'm running the node in background. and cosmos-sdk try to read from a memory buffer when no tty.
After I add the `--keyring-backend test` to `ethermintd start` it works. 
Maybe `ethermintd start` command should have `--keyring-backend test` as default, since it's usually running in background?
