### ISSUE TITLE
`eth_coinbase` address does not correspond to an account

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#112]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

Currently, what [coinbase api](https://github.com/tharsis/ethermint/blob/main/ethereum/rpc/eth_api.go#L145) returns is the consensus address, there's no correspond bank account for it, and I believe it's not the "address that staking rewards will be send to" as mentioned in comment. We should do a conversion([GetValidatorByConsAddr](https://github.com/cosmos/cosmos-sdk/blob/master/x/staking/keeper/validator.go#L36)) and return the validator address to avoid confusion.
But we don't have direct access to the keeper in eth rpc layer, we need to add a convert api in cosmos-sdk first.

**Comment by fedekunze** [comment]
correct, technically speaking, the coinbase address is the `address that mining rewards will be send to`. We can return the validator address in hex format by adding support to this staking query on the evm Query Service
