### ISSUE TITLE
enforce eip-155 to protect against replay

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#1122]
__Proposal:__ enforce eip-155 to protect against replay

__Current behavior:__

Right now, non-eip155 txs are still accepted, which opens room for replaying old ethereum tx on ethermint, similar to what happened on optimism recently.

__Desired behavior:__ 

Reject those txs and close the room for a potential attack.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
Agree, we introduce a parameter in the EVM to disable the `LegacyTx` type
