### ISSUE TITLE
`eth_gasPrice` returns a constant zero

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#115]
__Proposal:__ Implement `eth_gasPrice` rpc api

__Current behavior:__ returns zero

__Desired behavior:__ Better to return the `minimal-gas-prices` configured in current node.

__Use case:__ To keep compatible with existing web3 ecosystem

**Comment by fedekunze** [comment]
Thanks @yihuang, usually the `eth_gasPrice` returns the suggested value from the gas price oracle. I agree that the min gas price is a good short term solution 👍  

Btw, feel free to open a PR or assign yourself if you want to work on this issue next week

**Comment by thomas-nguy** [comment]
one of the easy fix is to return `ethermint.DefaultGasPrice` which is a constant value defined as 20

however would it be better to always use the min_gas_price defined in config whenever it is available and factorise the logic somewhere @fedekunze ?
