### ISSUE TITLE
Tx signature not set

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#118]
__System info:__ 

MacOs

__Steps to reproduce:__

Current transaction always fails on the 
`authante.NewValidateBasicDecorator()`

because the signature is always empty.

Should we set the signature in the builder 
```builder.SetSignature(xx)```  when building transaction ? (in doCall, Call, SendRawTransaction and SendTransaction)

__Expected behavior:__ [What you expected to happen]

Basic check pass

__Actual behavior:__ [What actually happened]

Return error "invalid signature"

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
> Current transaction always fails on the `authante.NewValidateBasicDecorator()`

where does it fail? the `msg.ValidateBasic()` doesn't check for the signature

**Comment by thomas-nguy** [comment]
It does check the length there 

https://github.com/cosmos/cosmos-sdk/blob/v0.42.5/types/tx/types.go#L91
