### ISSUE TITLE
blockGasMeter never set

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#119]
__System info:__ 
MacOs

__Steps to reproduce:__

In the `EthGasConsumeDecorator` antle handler, we are checking that the user has enough gas to pay the transaction.

We are setting the transaction gas meter to infinite 
```
	infCtx := ctx.WithGasMeter(sdk.NewInfiniteGasMeter())

```

But the block gas meter is not defined.

At this following line https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L301 
The program panic because of nil pointer exception (blockGasMeter return nil)

It is not clear how we should set the block gas limit. 
What is the difference between transaction gas meter and block gas meter? Maybe some documentation would help

__Expected behavior:__ 

Anter handler does not fails or manage the error gracefully

__Actual behavior:__ [What actually happened]

Nil pointer exception

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
> What is the difference between transaction gas meter and block gas meter? Maybe some documentation would help

The tx gas meter is the amount of gas available for that transaction and the block gas meter is the one available for all the operations in the block. See SDK [docs](https://docs.cosmos.network/master/basics/gas-fees.html)

> But the block gas meter is not defined.

The block gas meter is defined in begin block, so it's odd that it's panicking, can you provide more details to reproduce the error?

**Comment by thomas-nguy** [comment]
I just run the app in debugger mode and send a transaction. It is panicking at `EthGasConsumeDecorator` on this specific line.

I have also check the order. It seems `beginBlocker` is happening after the Anter Handler or it does not share the same context?

**Comment by thomas-nguy** [comment]
ok after investigation, 

the block gas meter is only set during "deliverTx"  (deliverState context)
https://github.com/cosmos/cosmos-sdk/blob/master/baseapp/abci.go#L179

But in case of simulate, it uses the checkStateContext and block gas meter is never set there
https://github.com/cosmos/cosmos-sdk/blob/master/baseapp/baseapp.go#L527
