### ISSUE TITLE
Can't initial staking 10,000,000 photon or 10^25 aphton

### ISSUE THREAD

**Issue by ppenter** [tharsis/ethermint#121]
I run along the tutorial but I change first gentx to 10000000000000000000000000aphoton and the error shown below.

Error code
![Screen Shot 2564-06-14 at 21 59 17](https://user-images.githubusercontent.com/55227490/121913697-d12c6e00-cd5b-11eb-8e2e-57c57400cbf8.png)

init.sh
<img width="758" alt="Screen Shot 2564-06-14 at 22 00 15" src="https://user-images.githubusercontent.com/55227490/121913820-eacdb580-cd5b-11eb-9b5b-c064fbf91ea7.png">

**Comment by fedekunze** [comment]
which codebase are you using? this repository or cosmos/ethermint? the `ethermintcli` binary has been deprecated and we now only use `ethermintd`

**Comment by ppenter** [comment]
> which codebase are you using? this repository or cosmos/ethermint? the `ethermintcli` binary has been deprecated and we now only use `ethermintd`

Oh I apologize. I post wrong github. you can close this issued.

**Comment by fedekunze** [comment]
yeah this repo is updated to the latest SDK and go-ethereum versions. Feel free to open any issues you encounter 👍
