### ISSUE TITLE
GetSender fails on Legacy TX Protected

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#127]
__System info:__ 

MacOS
__Steps to reproduce:__

Send a transaction with Metamask (transfer amount)

Metamask transaction is deserialize into a LegacyTx which does not contains ChainID (not supported in legacy?)

When trying to get the sender, it uses EIP-2930 implementation. 
The transaction is a LegacyTxType and Protected.

Current code fails at this point 

https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_signing.go#L272

Because tx.ChainId() return nil while s.chainId return 1337

__Expected behavior:__ 

Can get the transaction sender

__Actual behavior:__ 

Fails with ErrInvalidChainId

**Comment by fedekunze** [comment]
the sending will be returned according to the current chain config. By default, the chain config creates only `AccessListTx` because the Berlin fork will be enabled from height 0

**Comment by thomas-nguy** [comment]
yeah the current logic seems correct, however it fails with metamask transaction on the point previously mentionned.

I will look into it with more details..

**Comment by thomas-nguy** [comment]
after investigation, it seems that it is the opposite. 

The transaction chainId return 1337 (metamask config) but s.chainId return 0

Do we forget to set the chainId in the context?

```	k.WithChainID(ctx)``` is only called during genesis

**Comment by fedekunze** [comment]
> Do we forget to set the chainId in the context?
`k.WithChainID(ctx)` is only called during genesis

We should then set it on `BeginBlock` too I guess
