### ISSUE TITLE
types: reorganize types

### ISSUE THREAD

**Issue by khoslaventures** [tharsis/ethermint#131]
Geth seems to have much better organization of types. It would be great to reorganize our types to match or improve what they have.

https://github.com/ethereum/go-ethereum/tree/cc606be74c6f1f05b0b0a6226a400e734b9aac31/core/types

**Comment by fedekunze** [comment]
recommended folder structure from the SDK: https://docs.cosmos.network/master/building-modules/structure.html 

which structure do you have in mind?

**Comment by fedekunze** [comment]
recommended folder structure from the SDK: https://docs.cosmos.network/master/building-modules/structure.html 

which structure do you have in mind?
