### ISSUE TITLE
Transaction receipt/ Bloom Filter does not work

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#139]
__Steps to reproduce:__

I am opening this ticket for an already know issue. 

This feature is quite critical for most of the web3 tools which use the bloom filter and tx receipt to confirm that a transaction has been correctly inserted in a block. It would be nice to raise this to a higher priority.

Related to getBlockByNumber endpoint

__Expected behavior:__ 

Can detect when transaction has been processed

__Actual behavior:__ 

Currently bloomfilter return always 0x0

**Comment by yihuang** [comment]
the `SetBlockBloomTransient` is not called anyway, I'm not sure where it supposed to be called? @fedekunze

**Comment by fedekunze** [comment]
Calculating the block bloom from logs is the right approach 👍
