### ISSUE TITLE
cosmjs testing suite

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#167]
Create a testing suite on `tests/` that checks the compatibility of [cosmjs](https://github.com/cosmos/cosmjs) with Ethermint:

- [ ] key generation
- [ ] signing of SDK transactions 
- [ ] signing of EVM transactions

**Comment by thomas-nguy** [comment]
does cosmjs support signing EVM transaction?

**Comment by fedekunze** [comment]
not out of the box, you would probably need to sign either with web3 or ethers.

1. Create the transaction
2. Sign Ethereum way (populate v, r, s using signer)
3. Sign SDK way

Ideally, 2 and 3 should be a single step

**Comment by ashwinphatak** [comment]
* Is there any near term plan to add ethermint support to cosmjs?
* Should people just use evmosjs instead?
