### ISSUE TITLE
UI support for Metrics

### ISSUE THREAD

**Issue by khoslaventures** [tharsis/ethermint#168]
## Overview

We plan to list relevant metrics available through the SDK telemetry system for user engagement information such as the number of contracts deployed, amount transacted, gas usage per block, number of accounts created, number and amount IBC transfers to and from Ethermint, etc. 

These metrics will be displayed in a Dashboard UI in the form of charts. 

Docs: https://docs.cosmos.network/master/core/telemetry.html

## Current Status

We have the metrics but we are missing the UI.

**Comment by kanishkatn** [comment]
What sort of UI are you looking for? 

I feel a Grafana dashboard would fit best!
