### ISSUE TITLE
Include tx and tm service in cosmos api server

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#172]
__Proposal:__ Include tx and tm service in cosmos api server

__Current behavior:__ Missing some apis in api server

__Desired behavior:__
- register tx service and tendermint service to api server
- update swagger doc

__Use case:__ better UX

I tried it here: https://github.com/yihuang/ethermint/commit/0daebad41ed846b301622ab0911a589571934940, but get error in `/block/latest` api:
```
Unregistered interface types.Evidence
```

**Comment by fedekunze** [comment]
can you provide more info about the actionable items?

**Comment by yihuang** [comment]
> can you provide more info about the actionable items?

- add [these lines of code](https://github.com/yihuang/ethermint/commit/0daebad41ed846b301622ab0911a589571934940?branch=0daebad41ed846b301622ab0911a589571934940&diff=unified#diff-9a386eb3549036068ecda4e5a763971ddc30dc65828b75c70640353200464272R228) when start node.
- update proto files and swagger doc to latest cosmos-sdk.

Actually I've done above two in my branch, it's just I got the issue with some api.

**Comment by yihuang** [comment]
I think the reason of the error `Unregistered interface types.Evidence` is we are using multiple versions of tendermint at the same time.

**Comment by fedekunze** [comment]
@yihuang I still get the `Unregistered interface types.Evidence` error but it seems that your changes are already included
