### ISSUE TITLE
Implement `miner_` namespace

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#173]
https://geth.ethereum.org/docs/rpc/ns-miner

Check which endpoints apply, if not, return empty response with error (unsupported).

**Comment by prajjwol** [comment]
@fedekunze from the looks of it doesn't look like any of the endpoints apply to ethermint? 🤔

**Comment by fedekunze** [comment]
So miner_setEtherbase should set the withdraw address using the SDK distribution module. 

We can also update the minimum fees on the config file by using the miner_setGasPrice endpoint.

All the others should return error or empty response (zero value)
