### ISSUE TITLE
Support fetching pending nonce

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#176]
__Proposal:__ Support fetching pending nonce

__Current behavior:__ only support fetching from current deliver state

__Desired behavior:__ ethereum api supports query on `latest`/`pending`/historical block height state.

__Use case:__ 

Fetching pending nonce when sending a new transaction is a common pattern in web3 development.

Related code in go-ethereum: https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1475

I think it's tricky to implement, but I create this issue nonetheless.

**Comment by fedekunze** [comment]
See https://github.com/cosmos/ethermint/blob/3596d535e1e32113604c122ffbdb0c68fac35ba3/rpc/namespaces/eth/api.go#L1101-L1147
