### ISSUE TITLE
context should not stored in keeper

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#179]
__System info:__ ethermint main

__Steps to reproduce:__

Currently we store context in keeper, but keeper is shared in different tx modes (deliver/check/simulate) with different context. I suspect it's the root cause of some issue, not sure yet.
I think we better pass context around rather than store it in keeper.

**Comment by fedekunze** [comment]
I agree that storing the context in the keeper is an anti-pattern, and should be avoided. The main issue here that I encountered was the fact that you can't use the context in the `StateDB` interface

**Comment by yihuang** [comment]
> I agree that storing the context in the keeper is an anti-pattern, and should be avoided. The main issue here that I encountered was the fact that you can't use the context in the `StateDB` interface.

https://github.com/cosmos/ethermint/blob/development/x/evm/keeper/keeper.go#L36
the cosmos version used a separated struct for that, and copy it for different modes, does that make sense?

> 
> The alternative is to be consistent and document in the code when we are using the stored context and why

if say simulate and deliver mode runs concurrently, stored context won't work right? I'm not sure of current concurrency status of cosmos-sdk though.

**Comment by fedekunze** [comment]
> the cosmos version used a separated struct for that, and copy it for different modes, does that make sense?

No, we did a refactor because it didn't make sense to keep another separate type that also had access to state. Also, that type also stored the context in the fields so it won't solve this issue to use that same struct.

> if say simulate and deliver mode runs concurrently, then storing context won't work right? I'm not sure of current concurrency situation in cosmos-sdk though.

Cosmos and tendermint txs are deterministic, so I don't think it would be an issue to store the context in that regard.

**Comment by yihuang** [comment]
> > if say simulate and deliver mode runs concurrently, then storing context won't work right? I'm not sure of current concurrency situation in cosmos-sdk though.
> 
> Cosmos and tendermint txs are deterministic, so I don't think it would be an issue to store the context in that regard.

I mean in abci design, mempool/consensus/info connections could be served concurrently in theory, but I'm not sure of cosmos-sdk implementation on this, it seems to be single thread?

**Comment by fedekunze** [comment]
closing for now
