### ISSUE TITLE
`AddLog` failed when unmarshaling tx

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#187]
__System info:__ ethermint main branch

__Steps to reproduce:__

The (one of the) root cause of https://github.com/tharsis/ethermint/issues/139 is [unmarshal tx failed](https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/statedb.go#L576), since the txbytes is the wrapping cosmos tx not the ethereum msg.
But we don't have a txDecoder here.

**Comment by fedekunze** [comment]
the logic is the same one though, can you try with a test case to see the root error?

**Comment by yihuang** [comment]
> the logic is the same one though, can you try with a test case to see the root error?

I tried a erc20 transfer tx which emit log, and I can see the "ethereum tx unmarshaling failed" error log, and logs in receipt are empty.

**Comment by yihuang** [comment]
> the logic is the same one though, can you try with a test case to see the root error?

do you mean the serialization of `ethtypes.Transaction` and `MsgEthereumTx` is the same? I mean the `TxBytes` is serialization of that wrapping cosmos tx, not only the `MsgEthereumTx`.
