### ISSUE TITLE
Problem: `make` build and test the code

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#199]
`make` usually build the binary
so how about
`make` works as `make build` ?

**Comment by fedekunze** [comment]
we can add an alias 👍

**Comment by prajjwol** [comment]
@fedekunze do we want to change the current behavior of `make` here and add a new alias for what it's doing now? i.e. `tools build lint test`

**Comment by fedekunze** [comment]
yeah `tools build lint test` sounds good
