### ISSUE TITLE
Should be able to call estimateGas without from field

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#201]
__System info:__ 

MacOs

__Steps to reproduce:__

Current code fails with internal error, 

On ethereum this RPC call should be perflectly valid

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{ "to":"0x11f4d0A3c12e86B4b5F39B213F7E19D048276DAe", "data":"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"}],"id":1}'  -H "Content-Type: application/json" http://localhost:8545

```
__Expected behavior:__ [What you expected to happen]

Return gas estimate

__Actual behavior:__ [What actually happened]

Internal Error

**Comment by thomas-nguy** [comment]
@fedekunze @yihuang 

So far, using the simulate boolean, I can skip the ante handlers which requires a from field or a transaction signature
but I am facing an issue in `applyTransaction`

The `ApplyTransaction` will try to refund the unconsumed gas to the sender account and I need to skip this step in case `from` is empty (since I am skipping the ante handler that consume all the gas)

Not sure what is the best way to do it because I have no way to know if its a real transaction or a simulated one

Possible solution
- Try to pass simulate boolean in the tx (kind of dirty to do because we are breaking eth format)
- Create a new msg type `MsgEthereumSimulateTx` ( but there will be a lot of redundancy)
- Use a mock keeper DB context in case of simulate (seems hard to do)


Any suggestions?

**Comment by yihuang** [comment]
I think in go-ethereum, empty `from` is replaced by `0x0` address.

**Comment by thomas-nguy** [comment]
yeah this is fine but the issue is 
- in Ante handler , we are transferring total gas cost from `from account` to module account for gas paiements => fails because `0x0` has 0 coins => I can skip in case simulate boolean is true

- In ApplyTransaction, we are refunding 'from address' unconsumed gas from module account to `from account` => fails because module account has 0 coins. Need to skip when simulating but there is no possible way to know we are in a simulated context

**Comment by yihuang** [comment]
fixed by: https://github.com/tharsis/ethermint/pull/236
I think it's fixed
