### ISSUE TITLE
`eth.getTransactionReceipt` returns incorrect contract address during contract creation (Using Truffle)

### ISSUE THREAD

**Issue by FrancoCRO** [tharsis/ethermint#210]
__System info:__ 
```
Mac 11.3.1
Go 1.15.6
```

__Steps to reproduce:__

1. Create a simple contract using truffle, or remix, or geth
2. Acquire the contract address using `eth.getTransactionReceipt("txid")`

__Expected behavior:__ 
Verify if it's a contract using `eth.getCode("address")`, expect a long hex string, 

__Actual behavior:__ 
`getCode` returns `0x` instead

__Additional info:__ 
The correct contract address can be obtained using the code below
```
let Web3 = require("web3");
let web3 = new Web3();

let RLP = require("rlp");
let nonce = 2;
let sender = "0x097a365779F5B9F3B0CbA57faC67Fb493146eCDB";

let address = "0x" + web3.utils.sha3(RLP.encode([sender, nonce])).slice(12).substring(14);
```

**Comment by yihuang** [comment]
I think the contract address and `eth_getCode` api actually is correct, I managed to pass my test script written in web3.py.

- why `.substring(14)`?
- rlp encoding schema

```python
import rlp
import eth_utils
import web3


class ContractAddress(rlp.Serializable):
    fields = [
        ("from", rlp.sedes.Binary()),
        ("nonce", rlp.sedes.big_endian_int),
    ]


def main(txhash):
    w3 = web3.Web3(web3.providers.HTTPProvider("http://localhost:1317"))
    tx = w3.eth.getTransaction(txhash)
    receipt = w3.eth.getTransactionReceipt(txhash)

    # verify contract address
    expect_contract_addr = eth_utils.to_hex(
        eth_utils.keccak(
            rlp.encode(
                ContractAddress(eth_utils.to_bytes(hexstr=tx["from"]), tx.nonce)
            )
        )[12:]
    )
    print(
        "contract address, expected:",
        expect_contract_addr,
        "actual:",
        receipt.contractAddress,
    )
    assert expect_contract_addr == eth_utils.to_normalized_address(
        receipt.contractAddress
    ), "invalid contract address"

    print("get code back", len(w3.eth.getCode(receipt.contractAddress)))


if __name__ == "__main__":
    main("0x1ef1b28ecb62ef15a9102facf92b5512b2cb43ac5ec98a4ca8df485d0c9bca68")
```

**Comment by FrancoCRO** [comment]
I found out the problem, when I deploy the contract using Truffle, the `from` address somehow became `0x0000000000000000000000000000000000000000` and the `contractAddress` from  `eth.getTransactionReceipt` is calculated using zero address and corresponding nonce

**Comment by yihuang** [comment]
> I found out the problem, when I deploy the contract using Truffle, the `from` address somehow became `0x0000000000000000000000000000000000000000` and the `contractAddress` from `eth.getTransactionReceipt` is calculated using zero address and corresponding nonce

👍 I can reproduce it now.

**Comment by FrancoCRO** [comment]
Seems this problem also happen in remix
