### ISSUE TITLE
state sync don't fully work

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#211]
__System info:__ ethermint main branch

__Steps to reproduce:__

1. start devnet
2. start new node with state sync enabled
3. query new node for the tx and states

__Expected behavior:__ tx query succesfully

__Actual behavior:__ tx not found

__Additional info:__
- chain state works fine though, for example, query contract state with `eth_call` works.

**Comment by fedekunze** [comment]
cc: @khoslaventures

**Comment by fedekunze** [comment]
is the node indexing txs?

**Comment by yihuang** [comment]
> is the node indexing txs?

yes, it's configured in the same way as other nodes, with:
```
indexer = "kv"
```

**Comment by leejw51crypto** [comment]
strage,   then tx-indexing will not work after state-sync for other chains

**Comment by yihuang** [comment]
One thing we can do is issue the tx query against the state sync provider nodes in evm rpc.
Cross check the responses from multiple rpc nodes to make is trustless.

**Comment by JayT106** [comment]
> > is the node indexing txs?
> 
> yes, it's configured in the same way as other nodes, with:
> 
> ```
> indexer = "kv"
> ```
> 
> I think tendermint state-sync just don't sync tx indexes.

correct, the TM core only index events when the indexer received the `EventDataNewBlockHeader`

**Comment by JayT106** [comment]
The state-sync doesn't store full blocks before the latest snapshot, I think the indexing service will only work on the block/tx data after the snapshot height.

**Comment by yihuang** [comment]
> The state-sync doesn't store full blocks before the latest snapshot, I think the indexing service will only work on the block/tx data after the snapshot height.

yeah, that's the issue, but some evm web3 rpc apis rely on the indexings to work.

**Comment by JayT106** [comment]
Agree! better just use the normal sync. Otherwise, the TM core might need to implement the block back import (the indexer relies on the new block header event) after the snapshot synced. (It is the same as the normal sync just the node can join the network quicker)

**Comment by yihuang** [comment]
https://github.com/tendermint/spec/blob/master/rfc/005-reverse-sync.md

**Comment by JayT106** [comment]
@yihuang @fedekunze just checked the implementation of the reverse-sync in TM core. It only does the back-sync with light blocks. I think it's still not able to query the tx from the indexer because there is no indexing process during the light-block sync, also the light-block doesn't have the tx data.

**Comment by leejw51crypto** [comment]
how about tx indexing to part of merkletrie ?
to own module keeper?

**Comment by JayT106** [comment]
> how about tx indexing to part of merkletrie ?
> to own module keeper?
> 
> not using current paradigm

could you explain? I don't quite understand how to index the unseen transactions in a bootstrap new node using state-sync?

**Comment by JayT106** [comment]
@yihuang just wants to clarify the requirement. In this issue, does the requirement need to query the transactions processed before the snapsnot blocks of the statesync or only after the snapshot block(including the snapshot block)?

**Comment by yihuang** [comment]
> @yihuang @leejw51crypto just wants to clarify the requirement. In this issue, does the requirement need to query the transactions processed before the snapshot blocks of the statesync or only after the snapshot block(including the snapshot block)?
> 
> Also in the current code base, is every tx query not working or just the transactions before the snapshot block?

I only tested the transactions before the snapshot block, I suppose the tx after state-sync is properly indexed, so it should work, might need to confirm.

**Comment by JayT106** [comment]
@yihuang Okay. I will create a new feature issue on the Tendermint repo! And have a discussion here!
