### ISSUE TITLE
block 1's parent hash is 0x0, should be block 0's hash

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#215]
__System info:__ ethermint main branch

__Steps to reproduce:__

```
$ curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", true],"id":1}'  -H "Content-Type: application/json" http://localhost:1317 | jq ".result.hash"
"0x31d4f6a270f00c4a4908a8632ed0d15e9dabaaddc876502bd6bfcfbccbca16df"
$ curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", true],"id":1}'  -H "Content-Type: application/json" http://localhost:1317 | jq ".result.hash"
"0x31d4f6a270f00c4a4908a8632ed0d15e9dabaaddc876502bd6bfcfbccbca16df"
$ curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", true],"id":1}'  -H "Content-Type: application/json" http://localhost:1317 | jq ".result.parentHash"
"0x"
$ curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", true],"id":1}'  -H "Content-Type: application/json" http://localhost:1317 | jq ".result.parentHash"
"0x"
```

__Expected behavior:__ block1's parent hash equals block0's hash

__Actual behavior:__ block1 is identical to block0

__Additional info:__

**Comment by leejw51crypto** [comment]
also 0x0 is incorrect, too.
because hash is bytes
"", or "0x00", "0x0000", etc..

**Comment by crypto-facs** [comment]
There are two issues in here. 

- The block hash format that is currently being returned on the coinbase block is wrong as @leejw51crypto pointed out. I opened a separate issue [here](https://github.com/tharsis/ethermint/issues/221) for it and a respective PR

- The second issue is a bit more complicated. There is a mismatched count within the way Ethereum and Tendermint handle block counts. Ethereum block count starts from `0` whereas in Tendermint `0` is not a valid block number, the count starts from `1`. 
Currently, this is being handle in the code by returning the same block for `1` and `2`.
 In my opinion this can be really confusing.
This has direct impact to users on two main RPC endpoints (and probably different parts of the codebase I am not aware of):
 -`getBlockByNumber` 
 -`getBlockByHash`
 
 But if we decide to solve this to get a more accurate response we would have to manage ourselves the difference between what the user sees and what is return from Tendermint. Meaning on `getBlockByNumber` we would have to do a + 1 to the block height the user queries, and on `getBlockByHash` we would have to subtract (-1) the height of the block Tendermint returns.
 
 This might be complicated to maintain consistently and could also lead to unexpected errors. I would love to get some opinions

**Comment by leejw51crypto** [comment]
how about using the same block height for cosmos, eth?
make 0 block means genesis for both

**Comment by crypto-facs** [comment]
I think we could close this issue as the proposed solution is what is currently being done! 👌
