### ISSUE TITLE
Problem: separating port 1317 from 8545

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#216]
how about using port separately?
1317: cosmos
8545: web3

to ensure compatibility for each protocol

benefit is
we use cosmos txhash for 1317 port
and eth txhash for 8545 port

but this is relatively big task, though
🧐

**Comment by yihuang** [comment]
there is cosmos api server at different port?

**Comment by leejw51crypto** [comment]
eth apis are categorized, i think current implementation is OK
so close this issue.
