### ISSUE TITLE
`from` field became necessary in `eth_call` 

### ISSUE THREAD

**Issue by FrancoCRO** [tharsis/ethermint#224]
__System info:__ 
```
Mac 11.3.1
Go 1.15.6
using main branch 0fc3472705b617620687b32b99fbc305c6fc506c
```
__Steps to reproduce:__

1. Deploy a contract
2. Call a contract using `curl`, or using `eth.contract(abi).at("address")` at `geth`

__Expected behavior:__ 
Returns desired value

__Actual behavior:__ 
`code = NotFound desc = account eth1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqfdrqed not found`

__Additional info:__ 
Mentioned by Huang Yi as well on this thread
https://github.com/tharsis/ethermint/pull/178#issuecomment-869533571

Metamask is also using `eth_call` without `from` to acquire ERC20 information, which result in abnormality if the issue persists. 
<img width="1172" alt="Screenshot 2021-07-05 at 11 55 47" src="https://user-images.githubusercontent.com/63992327/124416854-7ac6b400-dd8a-11eb-90a4-66e6a2fd679e.png">

Getting `decimals()` of WBNB on BSC
```
$ curl https://bsc-dataseed.binance.org -X POST --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"to": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c", "data": "0x313ce567"}, "latest"], "id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000000000000000000000012"}
```

At Tharsis (Without `from` -> FAIL)
```
$ curl localhost:8545 -X POST --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"to": "0x5dcDf28cFc6D0A870bd73E5Ace15F80b5c3E8D23", "data": "0x313ce567"}, "latest"], "id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rpc error: code = NotFound desc = rpc error: code = NotFound desc = account eth1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqfdrqed not found: key not found"}}
```
At Tharsis (SUCCESS)
```
$ curl localhost:8545 -X POST --data '{"jsonrpc":"2.0", "method":"eth_call", "params":[{"from": "0xf7fdc4660b71fc1430fad24a3442608b619682bf", "to": "0x5dcDf28cFc6D0A870bd73E5Ace15F80b5c3E8D23", "data": "0x313ce567"}, "latest"], "id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000000000000000000000012"}
```
At Tharsis (Using geth)
![image](https://user-images.githubusercontent.com/63992327/124417883-c0847c00-dd8c-11eb-91e3-bb79948f1216.png)

**Comment by thomas-nguy** [comment]
should be fixed in this issue https://github.com/tharsis/ethermint/issues/201

**Comment by FrancoCRO** [comment]
I agree, closing this one first then
