### ISSUE TITLE
Problem: default denom is  aphoton

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#225]
how about changing to wei or gwei?
wei = 10^-18 eth
gwei = 10 ^-9 eth 

or something newone?
microeth or nanoeth?

**Comment by fedekunze** [comment]
Atto is the SI prefix unit used in the metric system for 1x10^18:

https://en.m.wikipedia.org/wiki/Atto-

We want to stick to international standards

**Comment by leejw51crypto** [comment]
aphoton can also men "one" photon

**Comment by fedekunze** [comment]
"a" is the official prefix
