### ISSUE TITLE
`eth_call` don't support historical block height

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#229]
__Proposal:__ To support do `eth_call` on historical block height.

__Current behavior:__ call `/app/simulate` which don't support historical block height.

__Desired behavior:__ do support

__Use case:__ web3 `eth_call` api supports historical block height.

https://github.com/cosmos/cosmos-sdk/issues/9636

Maybe better to use a custom query command, rather than reuse the `/app/simulate`.

**Comment by fedekunze** [comment]
isn't the block height passed to the `abci.RequestQuery`? which query command are you suggesting to use?

**Comment by yihuang** [comment]
> isn't the block height passed to the `abci.RequestQuery`? which query command are you suggesting to use?

we passed the block height to abci query, but `/app/simulate`'s implementation don't use that.
The issue I linked is about change the implementation, but simulate api might not designed for this purpose.

**Comment by leejw51crypto** [comment]
historical block height means
old block height ?
