### ISSUE TITLE
Problem: `make localnet_start` not working

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#234]
__Proposal:__  adding local network testing using 4 nodes

__Current behavior:__ make localnet_start not working
```
> [build-env 5/5] RUN make build-ethermint-linux:
#12 0.327 make: *** No rule to make target 'build-ethermint-linux'.  Stop.
```

__Desired behavior:__ replace localnet test with pystarport from pypi
instead of docker, run multiple process in one pc , for easier handling

__Use case:__ easy multi nodes setup is necessary for debugging and testing

**Comment by fedekunze** [comment]
I would prob deprecate this command and rely on `starport serve` instead. We can update the `config.yml` to start the chain with 4 validators

**Comment by fedekunze** [comment]
this was recently fixed
