### ISSUE TITLE
Return correct gas used amount in BlockByNumber and BlockByHash

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#235]
__System info:__ 

MacOs

__Steps to reproduce:__

Currently, we are returning the gas specified in the transaction. 
The gas used by the transaction is defined during the execution and not stored anywhere. We need to return this value in 
the receipt and blockInformation instead.

**Comment by fedekunze** [comment]
does this still apply?

**Comment by thomas-nguy** [comment]
For the receipt, I think it should return the correct result.

For GetBlockByNumber & GetBlockByHash, it still compute the gas used using the transaction input, so it is incorrect. It should use the result instead

**Comment by davcrypto** [comment]
Submitted PR for this issue
