### ISSUE TITLE
fix inconsistent logging levels

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#262]
too many logs are displayed
when --log_level fatal or panic
make only important messages displayed

consider
--log_level silent
no messsages are displayed, only writes to files

**Comment by fedekunze** [comment]
you can set up the node to `--log_level = error`. I think the main issue here is the inconsistency between the node and the JSON-RPC logs (which always run on `info`)

**Comment by leejw51crypto** [comment]
yes
