### ISSUE TITLE
gas estimation is not accurate

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#268]
__System info:__ ethermint main branch

__Steps to reproduce:__

1. set tx gas to the value returned by estimateGas api
2. execute tx, run out of gas

__Expected behavior:__ should just work

__Actual behavior:__ run out of gas

__Additional info:__ 

Might have to do a binary search like [go-ethereum](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L963).

Because the gasUsed returned by `EthCall` is not the peak gas needed during execution, due to different kinds of gas refund.

**Comment by leejw51crypto** [comment]
this is the value for estimate gas
Ganache: 0xa2ae = 41646
Tharsis: 0x52d4 = 21204

i'm wondering why the difference comes from?

**Comment by yihuang** [comment]
I guess the tharsis is the fully refunded one, while the ganache is the real peak gas limit needed to run the tx.
