### ISSUE TITLE
Support personal apis with different keyring backends

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#269]
__Proposal:__ Support personal apis

__Current behavior:__ limited supported

__Desired behavior:__ fully support

__Use case:__ web3 api compatibility

Status:
- `ImportRawKey`, implemented, hangs when running at background with file backend.
- `UnlockAccount/LockAccount`, not implemented
- `ListAccounts`, implemented
- `SendTransaction/Sign`, probably hangs when running at background with file backend

**Comment by leejw51crypto** [comment]
encrypt , decrypt too
consider embedded database

**Comment by fedekunze** [comment]
What's the status of this? we should prioritize this fix @yihuang @leejw51crypto

**Comment by fedekunze** [comment]
or maybe @thomas-nguy? this should be supported on mainnet

**Comment by thomas-nguy** [comment]
link to this issue

https://github.com/99designs/keyring/issues/85

Or we can just decide to implement it as an additional layer on ethermint?

**Comment by fedekunze** [comment]
> Or we can just decide to implement it as an additional layer on ethermint?

what are you proposing exactly? override the keyring?

**Comment by yihuang** [comment]
First of all, I think we can only target the `file` backend? for os backend, is it even possible to have a headless solution?
For the `file` backend, `unlock` could be implemented as caching the passphrase or private key in memory.
And in several places,  providinging a passphrase to the API through an in-memory buffer so it doesn't read stdin.

**Comment by davcrypto** [comment]
@tomtau @fedekunze helping on this

**Comment by davcrypto** [comment]
@fedekunze `FilePasswordFunc` for file backend has a hard dependency to cosmos-sdk which would be fixed to get input from stdin. Should ethermint has its own keyring config set up and give up this hard dependency?
