### ISSUE TITLE
Problem: tx indexing is not working after sync

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#270]
how about keeping tx-indexing as our own module, and keeper
so that state-sync support tx-indexing
as part of consensus

pro: easy to implement
con: waste of some space

**Comment by fedekunze** [comment]
txs shouldn't be kept in state, if it's not working then there's something wrong with the config or the SDK

**Comment by JayT106** [comment]
https://github.com/tharsis/ethermint/issues/211

**Comment by leejw51crypto** [comment]
same issue iwth #211
