### ISSUE TITLE
gas used in ethermint and geth devnet is different

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#279]
__System info:__ ethermint main branch, geth 1.10.4

__Steps to reproduce:__

1. start geth local devnet with genesis file: https://github.com/yihuang/web3-integration-tests/blob/master/tests/geth-genesis.json
2. start ethermint local devnet
3. test a erc20 contract transfer, check the result of estimateGas and gasUsed, they are significant different from each other on two networks. (34466 on geth vs 40266 on ethermint)

__Expected behavior:__ should be identical, or close enough.

__Actual behavior:__ very different

__Additional info:__

Clone repo https://github.com/yihuang/web3-integration-tests, and run:
```
$ nix-shell
$ pytest -v tests/test_erc20.py -k geth
```

**Comment by leejw51crypto** [comment]
check intrinsicgas ,  constant gas is different?

**Comment by thomas-nguy** [comment]
is it fixed with the binary search?

**Comment by yihuang** [comment]
yes, it's fixed by this one: https://github.com/tharsis/ethermint/pull/288
