### ISSUE TITLE
gas cost is different from go-ethereum

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#287]
__System info:__ ethermint main, geth recent version

__Steps to reproduce:__

1. run geth devnet with berlin hardfork activated
2. run ethermint devnet
3. compare the gas cost of same contract transaction

__Expected behavior:__ should be the same

__Actual behavior:__ different, after trace the opcode, the `SLOAD` cost 2900 on ethermint, but 2100 on geth

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by leejw51crypto** [comment]
check GetEthIntrinsicGas
