### ISSUE TITLE
EVM RPC can't startup because tendermint rpc not ready sometimes

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#292]
__System info:__ ethermint main branch

__Steps to reproduce:__

1. try to start ethermint devnet
2. the node fails to startup with error message:
```
EVM RPC Connecting to Tendermint WebSocket at
time="2021-07-15T08:07:08+08:00" level=fatal msg="Tendermint WS client could not start for  tcp://0.0.0.0:26657/websocket" error="Not Found"
```

__Expected behavior:__ should always start up succesfully

__Actual behavior:__ sometimes failed

__Additional info:__ 

- It don't happen every time, but quite frequent today. didn't experienced this before.
- In my setup, the nodes are restarted automatically, and when this happens, it keeps happens for every restart, but tendermint consensus moves on (keep generating new blocks).

**Comment by JayT106** [comment]
@fedekunze could you assign this issue to me? thanks!

**Comment by yihuang** [comment]
I think probably because I have setup http proxy environment variable at that time 🤦‍♂️

**Comment by yihuang** [comment]
closing for now, reopen if reproduced without proxy settings.
