### ISSUE TITLE
Start other network without forking

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#293]
__Proposal:__ Run other networks without forking

__Current behavior:__ Several chain parameters are static constants, not easy to change if not fork or significant copy-paste code.

__Desired behavior:__ easy to start another network by import ethermint as a module

__Use case:__ start other network with ethermint codebase.

## Approach 1
New network re-use the whole ethermint scaffolding, just make some constants customizable, mainly [these things](https://github.com/tharsis/ethermint/blob/main/app/app.go#L109).

## Approach 2
New network start with cosmos-sdk simapp standard scaffolding, possibly with it's own customization, only add necessary stuff for ethermint to run, mainly:
- add evm module
- custom ante handler
- extra app configuration (evm-rpc listen addresses)
- start evm rpc server in cli start command
- anything else?

**Comment by leejw51crypto** [comment]
how about approach 1,
what's the benefit of approach 2 ?

**Comment by yihuang** [comment]
> how about approach 1,
> what's the benefit of approach 2 ?

with approach 2, we would be more clear on what changes ethermint does on top of cosmos-sdk scaffolding, currently ethermint scaffolding is significantly different from cosmos-sdk one, I'm not sure which part is necessary which part is accidental. Also we can do our own customization, for example add other native modules.

**Comment by fedekunze** [comment]
> Several chain parameters are static constants, not easy to change if not fork or significant copy-paste code.

what are the chain parameters that you would like to change?

**Comment by yihuang** [comment]
> > Several chain parameters are static constants, not easy to change if not fork or significant copy-paste code.
> 
> what are the chain parameters that you would like to change?

Normally just these things https://github.com/tharsis/ethermint/blob/main/app/app.go#L109:
- address prefix
- bip44 coin type
- default home directory name

There's always possibility that we might want to add new native modules in the future though.

**Comment by fedekunze** [comment]
> Normally just these things https://github.com/tharsis/ethermint/blob/main/app/app.go#L109:

but you can change those by defining them in your `app.go`, you just need to define your prefix and home directory

**Comment by yihuang** [comment]
> > Normally just these things https://github.com/tharsis/ethermint/blob/main/app/app.go#L109:
> 
> but you can change those by defining them in your `app.go`, you just need to define your prefix and home directory. The approach 2 is what chains would usually use when importing external modules

Do you mean wrap the `EthermintApp` and override some methods?

Another issue is the cli commands is defined in main package, which seems to be not importable.
