### ISSUE TITLE
Get_Logs does not returns all logs

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#297]
__Steps to reproduce:__

run yarn test --network ethermint basic

On Contract: Counter, it expects 3 logs on subtracts but ethermint returns only 2

If we run against Ganache, it works fine

__Expected behavior:__ 

Get_logs should returns all the log for a specific contract address search

__Actual behavior:__ 

Some logs are missing (needs investigation)

__Additional info:__

[test_ok_log_ganache.log](https://github.com/tharsis/ethermint/files/6821273/test_ok_log_ganache.log)
[test_bad_log_ethermint.log](https://github.com/tharsis/ethermint/files/6821274/test_bad_log_ethermint.log)

**Comment by yijiasu-crypto** [comment]
In the test above, only logs from the first tx will be returned by calling `eth_getLogs`. Logs from 2nd tx are omitted
