### ISSUE TITLE
Optimize eth_getLogs efficiency

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#303]
__Proposal:__ 

GetLogs performance is quite bad at the moment. It will try to find logs matching the criterias by looping through all the blocks and transactions
It won't work well when the chain grow significantly. 

We should use the bloom filter to avoid checking block which are tested negative.

__Current behavior:__ [What currently happens]

Loop through all blocks/transactions/logs

__Desired behavior:__ [What you would like to happen]

Check only blocks which bloom filter returns positive

**Comment by leejw51crypto** [comment]
which  part, can i see the source?

**Comment by thomas-nguy** [comment]
https://github.com/tharsis/ethermint/blob/main/ethereum/rpc/namespaces/eth/filters/filters.go#L87

It seems bloom filter is used only for single block search (when blockhash is specifiied)

**Comment by leejw51crypto** [comment]
i see, check bloom filter for each block?

**Comment by fedekunze** [comment]
will close this one in favor of #563
