### ISSUE TITLE
Problem: remix hello world not working

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#306]
run:  http://remix.ethereum.org/
using: http://127.0.0.1:8545  ethermint

this source worked without any issue on truffle, etherjs 

1. deployment <- good
2. changing state <- not working 

solidity source
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

/**
 * @title Storage
 * @dev Store & retrieve value in a variable
 */
contract Storage {

    uint256 number;

    /**
     * @dev Store value in variable
     * @param num value to store
     */
    function store(uint256 num) public {
        number = num;
    }

    /**
     * @dev Return value 
     * @return value of 'number'
     */
    function retrieve() public view returns (uint256){
        return number;
    }
}
```

try to run `store`
![image](https://user-images.githubusercontent.com/51560997/125888584-e30804b2-42a0-46e1-95d7-cae575cd649a.png)

**Comment by leejw51crypto** [comment]
i used 8545 port directly, not meta-mask injected web3 apis.

**Comment by leejw51crypto** [comment]
not a bug,
increase gas limit, gas price,
and it worked

**Comment by zhangyelong** [comment]
Hi @leejw51crypto , do you have any ideas that I was trying to connect http://localhost:8545 Web3 Provider by Remix http://remix.ethereum.org/, but got error: `Not possible to connect to the Web3 provider. Make sure the provider is running, a connection is open (via IPC or RPC) or that the provider plugin is properly configured.`

I have enabled the cors of the api config in app.toml.

**Comment by zhangyelong** [comment]
Emm... Firefox works well but Chrome not
