### ISSUE TITLE
CreationCode makes ethermintd exploded

### ISSUE THREAD

**Issue by FrancoCRO** [tharsis/ethermint#308]
__System info:__ 
```
Max OS X
Main (d7c9656d7704e77ed0f71ea45755cadc25dbd979)
```

__Steps to reproduce:__

1. Deploy `CreationCode` with the code below, using remix or any tool you like (https://gist.github.com/FrancoCRO/b198c1dc6d63626e92cd00f7fedd9406)
2. Call `CODE_HASH`

__Expected behavior:__
Returns code hash

__Actual behavior:__ 
Ethermintd becomes unresponsive, and is crazy printing EVM stack logs for minutes, and you have to SIGKILL it

__Additional info:__ 
This CreationCode method is used by Uniswap-family swaps
The `PancakePair` contract code is obtained from here (https://bscscan.com/address/0x0eD7e52944161450477ee417DE9Cd3a859b14fD0#code)
And is called from here
(https://bscscan.com/address/0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73#code)

**Comment by FrancoCRO** [comment]
Seems it will eventually returns a result, but it takes ... 1078 seconds.
```
{"output":"a70eeb9bb3b548bd3404057cd53405c892d49801acca673e77238beb06b75b15","gasUsed":"0xcb2e","time":1078131106396}
```

**Comment by leejw51crypto** [comment]
nice catch

**Comment by fedekunze** [comment]
> Ethermintd becomes unresponsive, and is crazy printing EVM stack logs for minutes, and you have to SIGKILL it

you can run the node without the --trace flag to disable stack tracing

**Comment by leejw51crypto** [comment]
seems recursive calls itself

**Comment by FrancoCRO** [comment]
Yeah seems that with `--trace` turned off it returns result almost immediately. Thanks :D

**Comment by yijiasu-crypto** [comment]
this is not bug just printing too much to stdio I think

**Comment by leejw51crypto** [comment]
today i'll check this issue

**Comment by leejw51crypto** [comment]
> this is not bug just printing too much to stdio I think

agree

**Comment by leejw51crypto** [comment]
i'll crosscheck it's legitimately processed in evm

**Comment by leejw51crypto** [comment]
reproduced in metamask X remix

**Comment by leejw51crypto** [comment]
modifying now

**Comment by leejw51crypto** [comment]
submitted pr, it's simple one ^^;

**Comment by thomas-nguy** [comment]
should we close the issue?

**Comment by FrancoCRO** [comment]
> should we close the issue?

I think yes, if the limitable is at the stdio side
