### ISSUE TITLE
Problem: missing update of metamask

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#315]
update chainid and enough funds to be displayed correctly on metamask markdown
also make some name for 10^18 aphoton 
maybe photon?

for example)
1 aphoton  is displayed as zero in metamask

10000009999999981 aphoton
0.01 photon(?) == 10000009999999981 * 10^-18 aphoton

**Comment by thomas-nguy** [comment]
The current document is correct, if you use "PHOTON" as the symbol, then it will treat it as 10^18 * base unit which is aphoton
https://github.com/tharsis/ethermint/blob/main/docs/guides/metamask.md

Chain id may deserve more explanation

**Comment by leejw51crypto** [comment]
also when devnet  restart, sequence is used from previous network.
deleteAccount after devnet restart

**Comment by leejw51crypto** [comment]
and correct chain-id to prevent invalid block number

**Comment by leejw51crypto** [comment]
removed metamask cache, not a bug
