### ISSUE TITLE
Query could fail with block number returned by `eth_blockNumber` api

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#318]
__System info:__ ethermint main branch

__Steps to reproduce:__

1. start devnet
2. run script:
```python
import time

import web3

w3 = web3.Web3(web3.providers.HTTPProvider("http://localhost:1317"))
while True:
    no = w3.eth.block_number
    try:
        w3.eth.get_balance("0x57f96e6B86CdeFdB3d412547816a82E3E0EbF9D2", no)
    except:
        print("fail")
    else:
        print("success")
    time.sleep(1)
```

__Expected behavior:__ always success

__Actual behavior:__ fail sometimes

**Comment by leejw51crypto** [comment]
what's error message? not found?

**Comment by yihuang** [comment]
> what's error message? not found?

A panic, because the state correspond to the block height not exists.
