### ISSUE TITLE
Block time goes beyond system clock when time_iota_ms is 30s

### ISSUE THREAD

**Issue by calvinaco** [tharsis/ethermint#322]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

- Commit: c8b88a3a8bd46cc55e11fb616a0e1497d03f2400
- OS: macOS Catalina 

__Steps to reproduce:__

1. Create a Devnet using `./init.sh`
2. Run the chain for 4-5 blocks
3. Query http://127.0.0.1:26657/block
4. The block time is beyond the current time

__Expected behavior:__ [What you expected to happen]

- Block time should not go beyond system clock

__Actual behavior:__ [What actually happened]

- Block time is beyond system clock

__Additional info:__ [Include gist of relevant config, logs, etc.]

According to https://docs.tendermint.com/v0.32/tendermint-core/using-tendermint.html, this behaviour seems to be possible
> Minimum time increment between consecutive blocks (in milliseconds). If the block header timestamp is ahead of the system clock, decrease this value.

However, according to the latest doc it should be deprecated already: https://docs.tendermint.com/master/tendermint-core/using-tendermint.html

Having been said, the behaviour seems to match with the case.

**Comment by fedekunze** [comment]
Can you open an issue on Tendermint? I can try to push the team to prioritize a fix

**Comment by JayT106** [comment]
I guess this will solve the issue. but it's targeting in release v0.36
https://github.com/tendermint/tendermint/issues/2840
