### ISSUE TITLE
`eth_call` panic in some access list logic

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#335]
__System info:__ ethermint main

__Steps to reproduce:__

1. start devnet
2. deploy the test contract: https://gist.github.com/yihuang/428bf0e6fef9881db347024a1ef2866f
3. call the approve method

__Expected behavior:__ should success

__Actual behavior:__ estimateGas fail, error message shows panic happens in this line of code: https://github.com/ethereum/go-ethereum/blob/v1.10.4/core/vm/operations_acl.go#L49

__Additional info:__

**Comment by FrancoCRO** [comment]
https://gist.github.com/FrancoCRO/01387f315c638de038219b5ef1a1a467
Here is a further dig down

**Comment by yihuang** [comment]
Hmm, I think I got the basic idea what's going wrong, `PrepareAccessList` is called in ante handler, but not in `eth_call` or `eth_estimateGas`, since it don't call ante handler.
I think we should move into `ApplyMessage`.

**Comment by leejw51crypto** [comment]
https://eips.ethereum.org/EIPS/eip-2930
