### ISSUE TITLE
Problem: create_empty_blocks in config not working

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#351]
$HOME/.ethermint/config/config.toml
```
# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
create_empty_blocks_interval = "0s"
```

with this option, still empty blocks are being generated

**Comment by leejw51crypto** [comment]
use cosmos paradigm

**Comment by fedekunze** [comment]
I think this issue belongs to tendermint core. Can you create one there with your question?

**Comment by zhouyou123** [comment]
the problem persists
