### ISSUE TITLE
Document revert logic

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#356]
Create a comprehensive doc to fully understand the revert and snapshotting logic on the EVM module.

- usage of the `journal`  type on go-ethereum vs Ethermint for keeping track of state modifications
- usage of `Snapshot()` and `RevertToSnapshot(revision)`
- document revert logic: document `cacheCtx` and `commit()` logic that writes to store only when the state transition is successful

**Comment by yihuang** [comment]
If we added the journal, we might not need the cacheCtx.

**Comment by fedekunze** [comment]
@yihuang can you take on this issue, please? We need it for the audit 🙏

**Comment by yihuang** [comment]
> @yihuang can you take on this issue, please? We need it for the audit 🙏

sure
