### ISSUE TITLE
Problem: tidy up error display when address not found

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#357]
tx bank  send eth1.......sender eth1...receiver 1000000000000001aphoton --chain-id ethermint-2 --keyring-backend test  --fees 20aphoton

```
Error: key with address48B212A71EBBB202.................................36FDE2FBC51not found: key not found
```
add spaces for clear display
```
address _____eth_address_____________ (  ____bech32_address_________ ) not found
```

**Comment by leejw51crypto** [comment]
also , consider, if chain-id is different, just return immediately

**Comment by fedekunze** [comment]
this error seems to come from the SDK, can you check it there?

**Comment by leejw51crypto** [comment]
sure, i'll check

**Comment by leejw51crypto** [comment]
https://github.com/cosmos/cosmos-sdk/pull/9975
