### ISSUE TITLE
Problem: 8545, 8546 port not accessible on windows

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#370]
this command list ports which is not accessible for users
```
netsh interface ipv4 show excludedportrange protocol=tcp
```

8545, 8546 port is included , cannot bind on windows

need to add to document

**Comment by fedekunze** [comment]
is this still a bug? @leejw51crypto

**Comment by leejw51crypto** [comment]
i think windows problem,
i used port number over 10000, working fine.
close the issue
