### ISSUE TITLE
`GetCommittedState` don't query the committed state

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#376]
__System info:__ ethermint

__Steps to reproduce:__

In go-ethereum, `GetCommittedState` query the committed state before current tx processing begins, but in ethermint `GetCommittedState` returns current state, which could cause differences in gas calculation: https://github.com/ethereum/go-ethereum/blob/master/core/vm/gas_table.go#L138

__Expected behavior:__ same with go-ethereum

__Actual behavior:__ different

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
actually, the transient store is a bad idea because we would have to iterate over it... we can maybe set the original context on the ante handler and then use that one for the `GetCommittedState` query

**Comment by yihuang** [comment]
> actually, the transient store is a bad idea because we would have to iterate over it to `commit` the changes... we can maybe set the original context on the ante handler and then use that one for the `GetCommittedState` query?

The issue on relying on the `CatchContext` to implement this is, `CacheContext` can't be nested, when you call `CacheMultiStore` on an already cached store, you don't get an extra layer of cache, it only works when the original store is the `MultiStore` itself. So in situations like checkTx, query and unit testing, it don't work.
