### ISSUE TITLE
Problem with API initialisation

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#382]
__Steps to reproduce:__

start node without specifying api
```
ethermintd start --pruning=nothing --rpc.unsafe --keyring-backend test --trace --log_level info

```

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' -H "Content-Type: application/json" http://localhost:8545
``` 

Returns 

{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method eth_blockNumber does not exist/is not available"}}

__Expected behavior:__ [What you expected to happen]

ETH api available (it is supposed to be defined as default)

__Actual behavior:__ [What actually happened]

No Api initialized

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
can you check the app.yaml config value and see if the "eth" API is defined?

**Comment by thomas-nguy** [comment]
there is currently an issue with the app.yaml config generated. The template is wrong

it prints "[eth]" instead of ["eth"] for a string slice. 


Would eventually needs to correct it in cosmos SDK
