### ISSUE TITLE
Problem: no example for evm rpc api  

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#390]
include full flags inside comment
like this
```
# Example: "eth,txpool,personal,net,debug,web3"
```

to here
```

# API defines a list of JSON-RPC namespaces that should be enabled
api = "{{ .EVMRPC.API }}"
```

**Comment by crypto-facs** [comment]
Hey @leejw51crypto I beliece this didnt have the latest updates. This was added by @thomas-nguy yesterday on https://github.com/tharsis/ethermint/pull/385

**Comment by leejw51crypto** [comment]
checked, close the issue
