### ISSUE TITLE
Problem: with `info` option, log display is too verbose

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#393]
for this type
```
 INF ABCIQuery
 ```

how about  moving to debug?
also check other logs as well
only display important logs in `info` type (system-wide reporting)

in production, log-itself can be used as ddos attack

**Comment by fedekunze** [comment]
closing in favor of https://github.com/cosmos/cosmos-sdk/issues/8132. Let's discuss alternatives there 👍
