### ISSUE TITLE
Restructure JSON-RPC directory and rename server config

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#400]
given that we are supporting additional namespaces other than ethereum's now (eg: `cosmos_` namespace #386), we should restructure the rpc directory in a more clear way:

```
rpc/
    ethereum/
       backend/
       namespaces/
          eth/ 
          ...
    cosmos/
       namespaces/
          cosmos/
    apis.go
``` 
 
 
 Additionally, we should rename the `EVMRPCConfig` to `JSONRPCConfig` to reflect this change

**Comment by crypto-facs** [comment]
I will take this issue as I am currently restructuring this area for the `debug` namespace
