### ISSUE TITLE
Fail early on `StateDB` functions

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#410]
Most of the functions from `statedb.go` perform a no-operation (no-op) when an error is encountered. The problem is, that these functions don't have any context of whether previous calls failed or not. For example, both `GetCodeHash` and `GetNonce` require the account to exist before returning the value. 

Solution:

Introduce a `stateErr error` field on the `Keeper` and return early on every `StateDB` method if there is a previous error registered.

**Comment by yihuang** [comment]
Just panic should be good?

**Comment by fedekunze** [comment]
no, it shouldn't panic, just fail early

**Comment by yihuang** [comment]
https://github.com/ethereum/go-ethereum/blob/master/core/state/statedb.go#L299
In go-ethereum, the query apis just returns a empty value when things not found.

**Comment by tomtau** [comment]
being worked on @davcrypto

**Comment by davcrypto** [comment]
@tomtau yup, please help to assign to me first
