### ISSUE TITLE
`EnableCreate` and `EnableCall` params are not used

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#412]
Seems that they were removed at some point and we need to read them.

Action Item:

Update `x/evm/keeper/state_transition.go` to include both parameters. See below for the reference of old implementation:

https://github.com/cosmos/ethermint/blob/3596d535e1e32113604c122ffbdb0c68fac35ba3/x/evm/types/state_transition.go#L196-L198

https://github.com/cosmos/ethermint/blob/3596d535e1e32113604c122ffbdb0c68fac35ba3/x/evm/types/state_transition.go#L203-L205

**Comment by usermrcat** [comment]
hi, got it, thank you

вс, 15 авг. 2021 г. в 17:55, Federico Kunze Küllmer <
***@***.***>:
