### ISSUE TITLE
Test vesting accounts

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#419]
- [ ] Manually test the creation of vesting accounts and make them interact with the evm module
- [ ] Create unit tests in `types/account_test.go` that support vesting account versions of `EthAccounts`
- [ ] Create integration tests for transferring ERC20 tokens from and to vesting account versions of `EthAccounts`
- [ ] create documentation about the usage of vesting accounts with Ethermint

**Comment by khoslaventures** [comment]
Relevant: https://docs.cosmos.network/master/modules/auth/05_vesting.html
