### ISSUE TITLE
Problem: missing signature verification in ante handler

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#424]
there is no verify signature
sender == tx.sender
like general tx of cosmos
```
err := authsigning.VerifySignature(pubKey, signerData, sig.Data, svd.signModeHandler, tx)
```

in eth sig verification decorator

```
func (esvd EthSigVerificationDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, next sdk.AnteHandler) (newCtx sdk.Context, err error) {
```

**Comment by fedekunze** [comment]
signature verification is checked from the `TxData` using the `Sender` function

**Comment by leejw51crypto** [comment]
yes, confirmed it.
can it be included to eth ante handler?

**Comment by fedekunze** [comment]
it's already included https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L76

**Comment by leejw51crypto** [comment]
checked
