### ISSUE TITLE
Problem: default chanid is not compatible with metamask 

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#473]
ethermint_9000-1 not working with meta-mask (chainid 1 collides with mainnet)
how about `ethermint-9000-2` ? 

and mixing _ with - looking ambiguous
just `-` to all separators?

**Comment by fedekunze** [comment]
chain ID is 9000, not 1. Please refer to the docs https://ethermint.dev/basics/chain_id.html
