### ISSUE TITLE
Implement stacktrace for errors

### ISSUE THREAD

**Issue by khoslaventures** [tharsis/ethermint#50]
__Proposal:__ Add support for [palantir/stacktrace](https://github.com/palantir/stacktrace)

__Current behavior:__ Currently our errors are not being propagated via a stacktrace

__Desired behavior:__ We want to see the origin of an error

__Use case:__ Debug test errors and CI errors

- [x] x/evm/keeper
- [x] app/ante

**Comment by fedekunze** [comment]
Action Items (correct me if I'm wrong @khoslaventures):

- Replace `fmt.Errorf` with `stacktrace.NewError`
- Wrap all returned errors with `stacktrace.Propagate`

Ref: https://pkg.go.dev/github.com/palantir/stacktrace

**Comment by liamsi** [comment]
Don't mean to distract you guys but just out of curiosity: were there any particular reasons to use palantir's lib instead of this one for instance https://github.com/go-errors/errors

**Comment by fedekunze** [comment]
implemented
