### ISSUE TITLE
Address review comments from PR #436

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#502]
@yihuang I will merge this PR, but can you address the comments from the review in a follow-up PR?

_Originally posted by @fedekunze in https://github.com/tharsis/ethermint/pull/436#issuecomment-906532077_

**Comment by yihuang** [comment]
it seems most of the commands are already addressed, the only one left is: "thoughts of using ReportAlloc()?", actually I'm not familiar with this one, do we just need to put it at the beginning of the benchmark function?
