### ISSUE TITLE
Can't make install ethermint on macOS 10.15.7 

### ISSUE THREAD

**Issue by danburck** [tharsis/ethermint#505]
__System info:__ 
- main branch (commit: 0cdedfc1fd465c292504966a7833e8d2e8028c67) 
- macOS Catalina 10.15.7 
- 2.4 GHz 8-Core Intel Core i9
- `jq version 1.6`
- `go version go1.16.7 darwin/amd64`

__Steps to reproduce:__

1. Clone and build Ethermint using git:
```
git clone https://github.com/tharsis/ethermint.git
cd ethermint
make install
```

__Expected behavior:__  Command runs successfully and `ethermintd` binaries are installed

__Actual behavior:__ I get the following output and `/build` is empty

````
mkdir -p /Users/danielburckhardt/code/ethermint/build/
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=ethermint -X github.com/cosmos/cosmos-sdk/version.AppName=ethermintd -X github.com/cosmos/cosmos-sdk/version.Version=0.0.0-412-g0cdedfc1 -X github.com/cosmos/cosmos-sdk/version.Commit=0cdedfc1fd465c292504966a7833e8d2e8028c67 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.34.12 -w -s' -trimpath  ./...
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
````

__Additional info:__ 
I also tried running `make docker-build` but I get the following output:

```
# TODO replace with kaniko
docker build -t : .
invalid argument ":" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [docker-build] Error 125
```

Seems like docker is not implemented here. In the `Makefile` it looks like docker is trying to build with `DOCKER_IMAGE` and `DOCKER_TAG` but they are not defined in the file. In the `cosmos/ethermint` repo they we're defined.

**Comment by danburck** [comment]
Closing this issue as the binaries got correctly installed by fixing the [GOPATH](https://golang.org/doc/gopath_code).

The failing `make docker-build` error however still remains

**Comment by entergmode** [comment]
Hi @danburck , I still encounter this.

```
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=ethermint -X github.com/cosmos/cosmos-sdk/version.AppName=ethermintd -X github.com/cosmos/cosmos-sdk/version.Version=0.5.0 -X github.com/cosmos/cosmos-sdk/version.Commit=644ae50410b9efbe876e7269e26644ed0d968669 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.34.13 -w -s' -trimpath  ./...
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]
```

Mind sharing your fix? Thanks!

`make docker-build` also doesn't work.

**Comment by danburck** [comment]
@entergmode My problem was, that I hadn't installed Go correctly.  Make sure to add Go to your PATH. Checkout [The GOPATH environment variable](https://golang.org/doc/gopath_code#GOPATH)

**Comment by entergmode** [comment]
@danburck Thanks for the quick reply! I am falling into same path as yours now. Yeah i'm trying to understand what you point out here about the Go Path. As i just installed Go from here, https://golang.org/doc/install and that's it.

**Comment by entergmode** [comment]
@danburck i got it finally. Thanks to you man!

Gonna leave some note here for whoever new :).

1. You need to set Go Path. Can ignore and use the default one. 
`go env GOPATH`   // to check
2. Export path to that executable
`export PATH=$PATH:$(go env GOPATH)/bin`

Now you should be able to run `ethermintd` as it's built and stored there

**Comment by entergmode** [comment]
Though the other 2 options don't give me anything.

```
~/crypto/ethermint main !2 > make docker-build                                           07:07:41 PM
# TODO replace with kaniko
docker build -t : .
invalid argument ":" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [docker-build] Error 125
~/crypto/ethermint main !2 > go install github.com/tharsis/ethermint@latest              07:12:32 PM
go: downloading github.com/tharsis/ethermint v0.5.0
go install: github.com/tharsis/ethermint@latest: module github.com/tharsis/ethermint@latest found (v0.5.0), but does not contain package github.com/tharsis/ethermint
```

**Comment by danburck** [comment]
Hey @entergmode, glad to help!

If you read the Makefile, you see that there is still an open TODO for this.
