### ISSUE TITLE
Adding genesis account throws errors

### ISSUE THREAD

**Issue by danburck** [tharsis/ethermint#507]
__System info:__ 
- main branch (commit: 0cdedfc1fd465c292504966a7833e8d2e8028c67) 
- macOS Catalina 10.15.7 
- 2.4 GHz 8-Core Intel Core i9
- `jq version 1.6`
- `go version go1.16.7 darwin/amd64`

__Steps to reproduce:__

1. [Clone and build Ethermint using git](https://ethermint.dev/quickstart/installation.html#github)
2. [Initialize chain](https://ethermint.dev/guides/localnet/single_node.html#initialize-the-chain)
3. [Add genesis account](https://ethermint.dev/guides/localnet/single_node.html#adding-genesis-accounts).

__Expected behavior:__ Genesis account is added 

__Actual behavior:__ 
At last step 

```
ethermintd add-genesis-account my_validator 1000000000stake,10000000000aphoton
```

the following error is thrown: 

  ```
Error: failed to get address from Keybase: my_validator.info: key not found [cosmos/cosmos-sdk@v0.43.0/crypto/keyring/keyring.go:465]
  ```

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
Thanks @danburck, try adding  the --keyring-backend=test to the command. That should fix your issue

**Comment by danburck** [comment]
@fedekunze Thanks, I tried this before as well and it threw another error: 
```
Error: cannot add account at existing address ethm1ea6hpjry6qdee0hgnfsqzf2suckk0cw8d88l0w
```

**Comment by rkollar** [comment]
@Tectract Not sure what is the default home there, but if it isn't the same as the one in the last command, it won't work. Try removing `--home ...`.

**Comment by Tectract** [comment]
actually what I needed here was to add the --keyring-dir flag, so it could find that .info file it wanted, my command ended up being:

build/simd gentx my_validator 100000000stake --keyring-backend test --keyring-dir ~/.simapp --chain-id demo-testnet-hello-1 --home private/.simapp/

Hope it can help someone in the future. Cheers!
