### ISSUE TITLE
default keyring-backend not consistent with cosmos-sdk

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#511]
__System info:__ ethermint main branch

__Steps to reproduce:__

```
$ ./build/ethermintd keys add test
Enter keyring passphrase:
Re-enter keyring passphrase:

- name: test
  type: local
...

$ ./build/ethermintd keys show test
Error: test is not a valid name or address: decoding bech32 failed: invalid bech32 string length 4

$ ./build/ethermintd keys show test --keyring-backend file
Enter keyring passphrase:
- name: test
  type: local
...
```

__Expected behavior:__ the default value for keyring-backend should be consistent between different commands.

__Actual behavior:__ not consistent

__Additional info:__

ethermint set command line flag default value to `file`, but some commands read the value from `client.toml`, which is `os` by default.

**Comment by fedekunze** [comment]
thanks @yihuang feel free to open a PR with the fix

**Comment by yihuang** [comment]
> thanks @yihuang feel free to open a PR with the fix

Change the default value to `os` should be able to fix the issue, is that good?

**Comment by davcrypto** [comment]
Submitted PR for the fix
