### ISSUE TITLE
Metamask: RLP Decode Fails

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#52]
__System info:__
Macos
__Steps to reproduce:__

Not sure if I am something wrong, but if I try to send an amount using metamask, the transaction fails.

The logs from the node give me :

```
ERRO[0017] transaction RLP decode failed                 error="rlp: input string too long for uint64, decoding into (types.MsgEthereumTx)(*types.TxData).GasLimit" module=json-rpc
```

1. Start the node
2. Setup metamask with a valid account with initial amount. I setup gas limit with 21000 (min amount) and gas fee to 50
3. Send 1 photon to another address

__Expected behavior:__ 

Transaction Success

__Actual behavior:__ [What actually happened]

Error decoding the transaction

**Comment by thomas-nguy** [comment]
Some update

With latest branch. I am able to send the transaction with metamask without errors. But somehow the balance is not updated (transaction is not going through?) 

I will keep investigating

**Comment by thomas-nguy** [comment]
After investigation, I found that the tx is not broadcasted for some reason

**Comment by fedekunze** [comment]
thanks @thomas-nguy, can you paste any relevant logs?

**Comment by thomas-nguy** [comment]
Actually there is no error.

The rpc endpoint seems to work and the broadcast `asyncCtx.BroadcastTx(txBytes)` returns no errors.

But if I put a breakpoint or a log in the handler. I can see that it never goes through.

My node is showing this log sometime

```
E[2021-06-02|16:07:08.226] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:57180 err="websocket: close 1006 (abnormal closure): unexpected EOF"
I[2021-06-02|16:07:08.226] Stopping wsConnection service                module=rpc-server protocol=websocket remote=127.0.0.1:57180 impl=wsConnection
E[2021-06-02|16:07:08.226] error while stopping connection              module=rpc-server protocol=websocket error="already stopped"
E[2021-06-02|16:07:08.347] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:57181 err="websocket: close 1006 (abnormal closure): unexpected EOF"
I[2021-06-02|16:07:08.347] Stopping wsConnection service                module=rpc-server protocol=websocket remote=127.0.0.1:57181 impl=wsConnection
E[2021-06-02|16:07:08.347] error while stopping connection              module=rpc-server protocol=websocket error="already stopped"
```

I wonder if it is related?

**Comment by thomas-nguy** [comment]
I close this issue because the root cause is the same as #79
