### ISSUE TITLE
No existing method for native module to execute evm transaction

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#533]
__Proposal:__ Create a clean method to call for the scenario of a native module to execute an internal EVM transaction.

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__

In Cronos we have this [method](https://github.com/crypto-org-chain/cronos/pull/34/files#diff-1cf88287bb640036f7fdeabdc381fba5bd0dc2dc5625d94846fca9359f1f2990R19) that tries to executing an internal EVM tx by native module, currently, there's no clean method to call in ethermint side, so it has to call many lower level methods to do it. Fortunately those methods are public, but still, it would be better if we can decouple the two by doing the encapsulate at ethermint side.

The method is bigger than `ApplyMessage` because it also handles the results, smaller than `ApplyTransaction` because it execute message directly, rather than transaction.

**Comment by fedekunze** [comment]
@yihuang are you still working on this? Feel free to open a PR

**Comment by yihuang** [comment]
Working on it now, plan to make `ApplyMessage` works for internal call scenario, and `ApplyTransaction` is for external transaction.
