### ISSUE TITLE
server: db is never closed when passed into .start*

### ISSUE THREAD

**Issue by odeke-em** [tharsis/ethermint#538]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

Ethermint commit 2e45a0665edb5184377f857dc235eb7f14d11c94

__Steps to reproduce:__

If we read through this code https://github.com/tharsis/ethermint/blob/2e45a0665edb5184377f857dc235eb7f14d11c94/server/start.go#L163-L195 and https://github.com/tharsis/ethermint/blob/2e45a0665edb5184377f857dc235eb7f14d11c94/server/start.go#L224-L443
We can see that created a new LevelDB instance but when we shutdown at the end of each code section with defer, we never close those dbs. I examined the code for an EthermintApp but I don't see any .Close() anywhere either.

Kindly cc-ing my colleague @cuonglm with whom am performing the audit.

__Expected behavior:__ [What you expected to happen]
A .Close() before exiting

__Actual behavior:__ [What actually happened]
Missing .Close()
__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
is this the case as well for the SDK simapp and Gaia?

**Comment by cuonglm** [comment]
> is this the case as well for the SDK simapp and Gaia?

Seems right: https://github.com/cosmos/cosmos-sdk/blob/d5674a5d3e82dcf47c4744af339a819e110e89f0/server/start.go#L238

**Comment by odeke-em** [comment]
> > is this the case as well for the SDK simapp and Gaia?
> 
> 
> 
> Seems right: https://github.com/cosmos/cosmos-sdk/blob/d5674a5d3e82dcf47c4744af339a819e110e89f0/server/start.go#L238
> 
> 

Indeed the same exists for all of them so we shall need to file bugs in those as well.
