### ISSUE TITLE
all: avoid allocating objects just to infer the pointer type in error messages, just use (*T)(nil)

### ISSUE THREAD

**Issue by odeke-em** [tharsis/ethermint#551]
__Proposal:__ [Description of the feature]
There is a pattern of trying to type cast to specific types, and when this fails, in the error message, we use the %T format specifier to infer the type but for the object of type T we instead use (*T)(nil)

__Current behavior:__ [What currently happens]
In just one single file app/ante/eth.go, I can see lots of instances of such like:

https://github.com/tharsis/ethermint/blob/d376ff9b8e7270b0d797631dad9802a9caf12c6e/app/ante/eth.go#L194

https://github.com/tharsis/ethermint/blob/d376ff9b8e7270b0d797631dad9802a9caf12c6e/app/ante/eth.go#L126

https://github.com/tharsis/ethermint/blob/d376ff9b8e7270b0d797631dad9802a9caf12c6e/app/ante/eth.go#L72

https://github.com/tharsis/ethermint/blob/d376ff9b8e7270b0d797631dad9802a9caf12c6e/app/ante/eth.go#L277

https://github.com/tharsis/ethermint/blob/d376ff9b8e7270b0d797631dad9802a9caf12c6e/app/ante/eth.go#L351

__Desired behavior:__ [What you would like to happen]
Instead of

```go
sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "invalid transaction type %T, expected %T", tx, &evmtypes.MsgEthereumTx{}),
```

We should have

```go
sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "invalid transaction type %T, expected %T", tx, (*evmtypes.MsgEthereumTx)(nil)),
```

__Use case:__ [Why is this important (helps with prioritizing requests)]
No need to unnecessarily allocate memory when reporting an error.

cc-ing my colleagues @cuonglm @kirbyquerby in relation to the audit we are performing.

**Comment by TsarenkoKir** [comment]
I need some help! I need to change my Twitter nickname in Form.
https://notionforms.io/forms/ethermint-testnet-validators
I have some troubles with my Twitter. Admins, can you help me?

вс, 12 сент. 2021 г. в 13:15, Emmanuel T Odeke ***@***.***>:

**Comment by Muggle-Du** [comment]
I can work on this and try to make a pull request

**Comment by TsarenkoKir** [comment]
Thank you a lot 👍

Пт, 24 сент. 2021 г. в 11:09, Adu ***@***.***>:
