### ISSUE TITLE
eth_getTransactionReceipt does not return events in logs[]

### ISSUE THREAD

**Issue by crypto-steve-ng** [tharsis/ethermint#575]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

```
Ethermint commit: 742b6d1300a89c11d91c4c04030e687b3222f957
```

__Steps to reproduce:__

1. Create a simple smart contract with a function that emits event 
2. Deploy the contract 
3. Call the function which emit event
4. Call `eth_getTransactionReceipt` with the txn hash from step 3

__Expected behavior:__ [What you expected to happen]
`eth_getTransactionReceipt` should return the event in `logs: []` 

__Actual behavior:__ [What actually happened]
`eth_getTransactionReceipt` returns an empty `logs: []` 

__Additional info:__ [Include gist of relevant config, logs, etc.]
If we rolled back to an earlier commit eg. `644ae50410b9efbe876e7269e26644ed0d968669` -- `logs: []` is populated eg. 

```
...other attributes,
"logs": [
  {
    "address": "0xd0faba4634a1ce7c62eccc7c3976a68e82a84e7a",
    "blockHash": "0x40c358708d281d44d34f050487d1ade493550ab349cb4b31082a34e10d7444a0",
    "blockNumber": "0x8e0abd",
    "data": "0x0000000000000000000000000000000000000000000000000000000000000016",
    "logIndex": "0x39",
    "removed": false,
    "topics": [
      "0xcb8241adb0c3fdb35b70c24ce35c5eb0c17af7431c99f827d44a445ca624176a"
    ],
    "transactionHash": "0xf227f3de58c17ca72ada8f7e056bef9eb5069d2c2f7eeccd3b6fdd91209a9561",
    "transactionIndex": "0x1f"
  }
],
```

**Comment by wenmoonsir** [comment]
+1.
Some libraries rely on `logs` for confirmation to trigger event listeners. Empty logs breaks it
