### ISSUE TITLE
cannot connect via ibc

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#58]
after setting up cro devnet and ethermint devnet

i tried to open channel 
```
hermes create channel $MYIBC0 $MYIBC1 --port-a transfer --port-b transfer 
```

and encounter this error
```
May 28 16:48:02.649 ERROR ibc_relayer::foreign_client: [testnet-central-0 ->
 ethermint-2:07-tendermint-0]  failed CreateClient: error raised while creating
 client: failed sending message to dst chain (ethermint-2) with err: GRPC error: 
GRPC error: failed to decode Protobuf message: BaseAccount.pub_key: unexpected end group tag

Error: error raised while creating client: Create client failed (ClientCreate("failed \sending message to dst chain (ethermint-2) with err: GRPC error: GRPC error:
 failed to decode Protobuf message: BaseAccount.pub_key: unexpected end 
group tag"))

```

**Comment by leejw51crypto** [comment]
## generating address for hermes
```
hermes keys restore ethermint-2  -m "my mnemonics" -t 118
```

## generating address for ethermint
ethermind keys add mykey --recover
--using the same mnemonics

both addresses are different

## different address generation
etherment: pubkey->sha256->last 20 bytes -> bech32
hermes, cosmos: pubkey->sha256->ripemd160-> 20 bytes -> betch32

**Comment by leejw51crypto** [comment]
would it be possible for cosmos rpcs using cosmos-style bech32 address?
and for eth rpcs using eth address?

**Comment by fedekunze** [comment]
> would it be possible for cosmos rpcs using cosmos-style bech32 address?
and for eth rpcs using eth address?

Isn't that the case already? 

> both addresses are different

this might be an issue from hermes. We have compatibility tests in the `crypto/hd/` package. Feel free to check them first and  add any additional test case to check for additional compatibility

**Comment by leejw51crypto** [comment]
i see,
hermes follow  legacy address generation , pubkey -> sha256->ripemd160->get 20 bytes
if we change ethermint address generation for bech32, will it make affect other eth side codes?

**Comment by fedekunze** [comment]
I think the Hermes key would have to be generated using an ethereum library and then create the `bech32` address from it. That's the flow we are using for our keys at least

**Comment by thomas-nguy** [comment]
closing the issue because it will be fixed on hermes
