### ISSUE TITLE
evm: in-process store migrations

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#601]
The EVM module is missing the in-process store migrations.

- https://docs.cosmos.network/master/core/upgrade.html#add-storeupgrades-for-new-modules

**Comment by yihuang** [comment]
it seems EVM module's storage and parameters didn't change after 0.7.2 release, the only migration needed is adding the feemarket module, but that can be done in the app upgrade handler directly I think.

**Comment by fedekunze** [comment]
@yihuang we should still add the command though. Otherwise, the genesis.json is going to be huge because of the contract code and storage
