### ISSUE TITLE
Problem: tx log attribute value is not parsable by some clients

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#614]
__System info:__ ethermint main

__Steps to reproduce:__

1. rust client expect the attribute value to be base64 encoded utf-8 string, while we encoded the tx log as bytes.

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ 

https://github.com/informalsystems/tendermint-rs/issues/1003

One solution is to encode the log in JSON in ethermint side.

**Comment by thomas-nguy** [comment]
linked to this issue https://github.com/informalsystems/tendermint-rs/issues/1003
