### ISSUE TITLE
Geth v1.10.9 JSON-RPC endpoints

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#623]
Some RPC endpoints that need to be added/revised after merging #231:

- eth_resend
- eth_fillTransaction
- eth_feeHistory
- eth_maxPriorityFeePerGas
- personal_sendTransaction: updates
- debug_intermediateRoots
- personal_unpair
- personal_initializeWallet
- personal_listWallets

**Comment by Muggle-Du** [comment]
personal_sendTransaction
#713

**Comment by Muggle-Du** [comment]
debug_intermediateRoots
#715

**Comment by Muggle-Du** [comment]
personal_Unpair 
#730

**Comment by Muggle-Du** [comment]
personal_initializeWallet
#738

**Comment by Muggle-Du** [comment]
personal_listWallets
#745
