### ISSUE TITLE
Problem: EVM keeper keeps intermediate states inside

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#664]
## The States
- `ctxStack`
- `stateErr`

## The problem
- It's error-prone to have to write `WithContext` all the time.
- context stack makes the situation even more complex.

## Proposal

Since the current design is to satisfy the `StateDB` interface, we can make a `StateDB` struct on the fly inside the `ApplyMessage`, and the keeper is clean from the mutable states, and pass the `ctx` around in the keeper methods.

**Comment by thomas-nguy** [comment]
I think this will be fix with #729

**Comment by yihuang** [comment]
> I think this will be fix with #729

yes, the fix is included there.

**Comment by yihuang** [comment]
fixed by https://github.com/tharsis/ethermint/pull/729
