### ISSUE TITLE
Inconsistent transaction hashing with Tendermint

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#67]
The hash that a user or library would expect from sending an ethereum tx over JSON-RPC doesn't match the one provided by the `ResponseDeliverTx` on Tendermint.

ref: https://github.com/tendermint/tendermint/issues/6539

**Comment by yihuang** [comment]
If don't modify tendermint itself, might need to store the hash relationship on chain?

**Comment by fedekunze** [comment]
that's an option, but we would have to prune the entries at some point. The map would have to be `eth hash --> tm hash` (querying by tm hash should already work fine)

**Comment by yihuang** [comment]
another thing about tx hash is, if we maintain hash relationship by ourself, we might be able to support multiple messages in one tm tx, just maintain the map of `eth tx hash -> (tm hash, msg index)`, if we customize the tm hash, we stick with 1-to-1 map of evm tx and tm tx.

**Comment by fedekunze** [comment]
Let's implement the map as a short-term solution. The update to Tendermint probably won't be included in a release soon... 
cc: @marbar3778

**Comment by yihuang** [comment]
We already emit the eth tx hash in events, so as long as enabled indexing in tendermint, we can query that in rpc api directly.
Sounds good as a temporary solution before we finally customize tendermint.
