### ISSUE TITLE
Problem: missing json rpc of eth_feeHistory 

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#685]
revise or add eth_feeHistory

**Comment by leejw51crypto** [comment]
reward computed,
now working on like this
1. run devnet
2. create a lot of txs with different fees
3. test fee_history
then will submit the pr

**Comment by fedekunze** [comment]
@leejw51crypto any updates on this?

**Comment by leejw51crypto** [comment]
test is done, refactoring now
will submit pr shortly

**Comment by leejw51crypto** [comment]
in cr
