### ISSUE TITLE
Problem: need to revise or add eth_maxPriorityFeePerGas rpc call

### ISSUE THREAD

**Issue by Muggle-Du** [tharsis/ethermint#687]
__Proposal:__ [Description of the feature]
need to revise or add rpc call eth_maxPriorityFeePerGas
__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by Muggle-Du** [comment]
evmbackend will fetch the latest suggested gas tip capacity from feemarket QueryClient, which requires adding messages in query.proto and regenerating the corresponding codes, and implementing the grpc methods of GetGasTipCap for feemarket keeper.
@yihuang suggests that tendermint will not order the txs in mempool, while this rpc is mainly involved with the priority of tx orders. So will return to this rpc call after finish other finishing other rpc calls.

**Comment by yihuang** [comment]
Maybe return some constant configurable values, to make the web3 client happy? Is any client depends on this API to work?

**Comment by Muggle-Du** [comment]
No, MaxPriorityFeePerGas is only used as public api for suggesting gas tip cap.
But SuggestTipCap is used by both MaxPriorityFeePerGas, SetTxDefaults and GasPrice public api

**Comment by fedekunze** [comment]
What are the actionable items here?

**Comment by Muggle-Du** [comment]
> are then any actionable items here?

Will come back after finishing other rpc endpoints

**Comment by Muggle-Du** [comment]
> are then any actionable items here?

Will come back after finishing other rpc endpoints

**Comment by Muggle-Du** [comment]
since currently tendermint will not consider the priority of txs based on gas price tip cap, should we return the minimum gas price of chain defaults or return the suggested gas tip cap by sampling from history gas price tip cap?
Which one do you think is more appropriate? @fedekunze

**Comment by Muggle-Du** [comment]
cosmos-sdk is now working on tendermint mempool prioritization (https://github.com/cosmos/cosmos-sdk/issues/9962), and it would be more appropriate to consider the dynamic maxPriorityFeePerGas at that time.
I will close the issue and let the JSON-RPC endpoint act in the current way.
