### ISSUE TITLE
fix JSON-RPC block `extraData`

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#69]
Ref: https://github.com/cosmos/ethermint/issues/814

**Comment by yihuang** [comment]
the `extraData` is a field of block, I think it's just arbitrary data created by miner.

**Comment by yihuang** [comment]
It seems the original issue is more about failed to decode "0x0" as hex data? But isn't "0x0" is used everywhere as an abbreviation of empty bytes?

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
yes , it seems formatting issue, i will modify it which satisfies the condition

**Comment by fedekunze** [comment]
related #173

**Comment by leejw51crypto** [comment]
"extraData":        hexutil.Uint64(0),
but i think, it's not uint64, it's 32 bytes buffer hex , i'll write pr , too

hex decode from "0x0" can cause decoding failure

must be even  number or "", "0x00", "0x0010" etc

**Comment by leejw51crypto** [comment]
writing the code, submit pr soon
