### ISSUE TITLE
Implement `debug_` namespace

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#71]
Implement JSON-RPC `debug_` namespace: https://geth.ethereum.org/docs/rpc/ns-debug

Imp: https://github.com/ethereum/go-ethereum/blob/master/internal/debug/api.go

**Comment by crypto-facs** [comment]
Hey guys, has there been any progress on this? Some endpoints from this namespace are also required by `blockscout` for the block explorer. Mainly the `debug_traceTransaction` method.

**Comment by fedekunze** [comment]
hey @crypto-facs, we haven't yet implemented it. We added it to the current sprint cycle to try tackle it

**Comment by crypto-facs** [comment]
Awesome! Thanks for tackling this. Let me know if I can be of any help.
