### ISSUE TITLE
Problem: contract call which does lots of message calls is slow to execute

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#710]
__System info:__ ethermint main

## Test Contract

```solidity
pragma solidity ^0.6.6;

contract Inner {
	event TestEvent(uint256);
    function test() public returns (uint256) {
        emit TestEvent(42);
        return 42;
    }
}

// An contract that do lots of message calls
contract TestMessageCall {
    Inner _inner;
	constructor() public {
        _inner = new Inner();
	}

    function test(uint iterations) public returns (uint256) {
        uint256 n = 0;
        for (uint i=0; i < iterations; i++) {
            n += _inner.test();
        }
        return n;
    }
}
```

## EstimateGas Slow

When call `eth_estimateGas` for the `test(40000)` contract method call, the web3 HTTP client timeout, the node log shows it takes 17 seconds to finish.
A single `eth_call` can be finished in 584ms, and the binary search in estimateGas did `ceil(log2(25000000)) = 25` number of calls, it sums up to `25 * 584ms = 14` seconds, close to what we see in the `eth_estimateGas` call.

Solution:
- improve the execution speed of each call
- lower the internal gas cap (so out of gas tx will fail earlier, and estimateGas will do less iterations in the worst case).

## Tx Execution Slow

Further investigation shows that the [actual execution of the tx is even slower](#issuecomment-957105725), a single run of the tx takes 30 seconds, [the profile](#issuecomment-957101207) shows the hotspot is in the commit of a deep context stack.

Solution:
- might have to refactor StateDB to use journal log approach like go-ethereum to implement the snapshot/revert.

__Expected behavior:__ RPC API and transactions should return fast

__Actual behavior:__ blocked for dozens of seconds

__Additional info:__

Compiled contract:
[TestMessageCall.json.zip](https://github.com/tharsis/ethermint/files/7451303/TestMessageCall.json.zip)

**Comment by yihuang** [comment]
I tried same script with geth and same gas limit, it's much faster, the request returns normally:

```
ValueError: {'code': -32000, 'message': 'gas required exceeds allowance (24926833)'}
```

**Comment by leejw51crypto** [comment]
how about logging the loop count which calls evm evaluation in binary searching?
time for each call
total call count

maybe too many calls?

**Comment by yihuang** [comment]
> how about logging the loop count which calls evm evaluation in binary searching? time for each call total call count
> 
> maybe too many calls?

it's worst case of binary search, so it should be around `log2(25000000) = 24.57`

> 
> starting gas allowance maybe too high? possible solution is lowering default gas allowances?

yeah, possibly.

**Comment by yihuang** [comment]
I did a single `eth_call`, the logged execution time is `584.998496ms`, and `584.998496 * 25 = 14624.9624ms`.

**Comment by leejw51crypto** [comment]
25 times of search count is not bad, 
can we reduce evm call time ?
584 ms == 0.5 seconds

**Comment by yihuang** [comment]
<img width="302" alt="Screen Shot 2021-11-02 at 12 54 14 PM" src="https://user-images.githubusercontent.com/236070/139788870-3bd2d7a9-2e78-42c7-9e23-828635149e2d.png">

I did a profile, most of the time spent on the commit of context stack.

**Comment by yihuang** [comment]
The benchmark: https://github.com/yihuang/ethermint/tree/bench-tx
Profile: `go test -v ./x/evm/keeper -v -run="^$" -bench="BenchmarkMessageCall" -cpuprofile profile.out`.
