### ISSUE TITLE
No need to support raw eth tx in default tx encoder/decoder

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#711]
__Proposal:__ don't support raw eth tx in default tx decoder

__Current behavior:__ currently it tries to decode `ethtypes.Transaction` first then fallback to the cosmos-sdk one.

__Desired behavior:__ don't try to decode `ethtypes.Transaction` at all.

__Use case:__

- Since the RPC API always wraps the eth tx in a cosmos standard tx, no need to decode it in the tx decoder.
- There could be issues if some cosmos tx encoding is identical with an eth tx, it's rare though.

**Comment by fedekunze** [comment]
yeah, agree. There it shouldn't be the case. Let's remove it and use the default decoder from the SDK
