### ISSUE TITLE
Problem: need to add rpc method debug_intermediateRoots

### ISSUE THREAD

**Issue by Muggle-Du** [tharsis/ethermint#715]
debug_intermediateRoots is not supported yet.
need to implement debug_intermediateRoots in rpc/ethereum/namespaces/debug/api.go and other related files.

**Comment by leejw51crypto** [comment]
i'll do this task after feehistory

**Comment by leejw51crypto** [comment]
for intermediatesRoots, it need to use trie directly
to get temporary worldstate roothash.

```
func (s *StateDB) IntermediateRoot(deleteEmptyObjects bool) common.Hash {
	// Finalise all the dirty storage states and write them into the tries
	s.Finalise(deleteEmptyObjects)


........
	// Track the amount of time wasted on hashing the account trie
	if metrics.EnabledExpensive {
		defer func(start time.Time) { s.AccountHashes += time.Since(start) }(time.Now())
	}
	return s.trie.Hash()
}
```

so 
1. add api handler
2. return empty hash for each tx

**Comment by fedekunze** [comment]
let's return an empty hash on the RPC for now and create a new issue to implement intermediate roots @Muggle-Du

**Comment by Muggle-Du** [comment]
> let's return an empty hash on the RPC for now and create a new issue to implement intermediate roots @Muggle-Du

ok
