### ISSUE TITLE
x/evm/keeper: (*ContextStack).RevertAll might be invalid and retain the bottom most context with a [0:1] slicing

### ISSUE THREAD

**Issue by odeke-em** [tharsis/ethermint#726]
While reading through the code I noticed this method https://github.com/tharsis/ethermint/blob/882dd4e2e3664a6a9a04f16bb508becf35d9ecb5/x/evm/keeper/context_stack.go#L104-L109 and that doc says that it discards all the cache contexts.

However, when we go into the actual code, we see
https://github.com/tharsis/ethermint/blob/882dd4e2e3664a6a9a04f16bb508becf35d9ecb5/x/evm/keeper/context_stack.go#L65-L80

but pay attention to this line exactly that performs the discarding
https://github.com/tharsis/ethermint/blob/882dd4e2e3664a6a9a04f16bb508becf35d9ecb5/x/evm/keeper/context_stack.go#L80

essentially reslicing from `[0: target+1]` which boils down to `target=0` so `[0:1]` but unfortunately that'll ALWAYS have the top most element regardless of how many elements were there unless the length was 0 and in which case there was already a filtration to return an error if len(...) < target

Here is a simple exhibit.

Kindly cc-ing @fedekunze @khoslaventures

**Comment by fedekunze** [comment]
I think is a doc issue as we always want to maintain at least one context in the stack. @yihuang can you confirm?

**Comment by yihuang** [comment]
https://github.com/tharsis/ethermint/blob/882dd4e2e3664a6a9a04f16bb508becf35d9ecb5/x/evm/keeper/context_stack.go#L94-L102

`RevertToSnapshot` is this one, and `RevertToSnapshot(n)` will not keep the revision `n`.

`CommitToRevision(n)` is expected to keep the revision `n`, only remove ones after it.
