### ISSUE TITLE
ante: check that sender is a EOA

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#73]
Actionable Items:

- Add check on `AnteHandler` to check if the user is an EOA
  - Note: need to pass an infinite gas meter to call `evmKeeper.GetCodeSize` and then reset to the original gas meter

Ref: https://github.com/ethereum/go-ethereum/pull/23002

**Comment by albertchon** [comment]
Wouldn't it be more efficient to just check the code hash? So either `k.GetCodeHash(addr) == common.Hash{}` or using `store.Has` for efficiency
```
        ...
	hash := k.GetCodeHash(addr)
	store := prefix.NewStore(k.ctx.KVStore(k.storeKey), types.KeyPrefixCode)
	return store.Has(hash.Bytes())
```
Btw common.Hash is just an array of bytes so you use the direct equality operator https://golang.org/ref/spec#Comparison_operators
