### ISSUE TITLE
Inconsistent baseFee check logic in code

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#755]
__System info:__ ethermint main

Following the discussion here: https://github.com/tharsis/ethermint/pull/671#discussion_r733562536, @fedekunze 

__Steps to reproduce:__

Currently, different places have different logic to check base fee:
- https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/state_transition.go#L36
- https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L366

Better to encapsulate a common logic to do this.

__Expected behavior:__ consistent way to check base fee.

__Actual behavior:__ inconsistency

__Additional info:__

**Comment by yihuang** [comment]
```
if not london_hardfork {
    # reject DynamicFeeTx
    # no `baseFeePerGas` field in block response
    # baseFee = nil
} else {
    # allow DynamicFeeTx
    # add `baseFeePerGas` field in block response
    if feemarketParams.NoBaseFee or height < feemarketParams.EnableHeight {
        # baseFee = 0
    } else {
        # init baseFee to initBaseFee and adjust later
    }
}
```

**Comment by thomas-nguy** [comment]
It looks reasonable to me.

For the case `NoBaseFee` or `height < feemarketParams.EnableHeigh`
The cost of the transaction will be only the gas-cap which will be the local value per validator (min-gas-price). In that case we are also consistent with previous behavior when london hard fork is not activated
