### ISSUE TITLE
Add mergify bot backport functionality

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#756]
Automatically backport PRs to `release/0.7.x` branch based on PR label

Ref: https://github.com/cosmos/cosmos-sdk/blob/master/.mergify.yml

**Comment by fedekunze** [comment]
@tomtau @yihuang @thomas-nguy this will ease the backporting process for you guys

**Comment by thomas-nguy** [comment]
just by curiousity, how does the bot handle merge conflict?

**Comment by tomtau** [comment]
@thomas-nguy AFAIK it won't open a PR if there's a conflict... one can set `ignore_conflicts` https://docs.mergify.com/actions/backport/#options in which case, it'll just open the PR with conflicts and a maintainer needs to manually resolve it (either in GitHub UI or by directly working on the branch the bot created)
