### ISSUE TITLE
Optimize tx index lookup in web3 rpc

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#760]
__Proposal:__ Optimize tx index lookup in web3 rpc

__Current behavior:__

Currently, the tx index is looked up by loading all the eth transactions in the block and iterating through them.

__Desired behavior:__

A more efficient way could be emitting the tx index into cosmos events, fetched by query tx result.

__Use case:__

Optimize performance of web3 rpc api.

**Comment by fedekunze** [comment]
sounds good to me 👍

**Comment by yihuang** [comment]
I'll work on this.
