### ISSUE TITLE
Probem: missing nonce ci test with massive txs

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#761]
let nonce = await this.web3.eth.getTransactionCount(from_addr);
nonce is incorrect

```
Caused by: invalid nonce; got 407, expected 692: invalid sequence
sendtx error Error: Returned error:  --- at github.com/tharsis/ethermint/app/ante/eth.go:222 (EthNonceVerificationDecorator.AnteHandle) ---
```

**Comment by thomas-nguy** [comment]
I wonder if it is because you query at block n and  when you send, its already block n+1 so the value of the nonce already changed?

**Comment by leejw51crypto** [comment]
i'll check more,
some gettxcount doesn't return nonce of the account.
so in next try, send-tx cannot work

**Comment by leejw51crypto** [comment]
i'll do this task~

**Comment by fedekunze** [comment]
@leejw51crypto can you add the fuzz tests to the JSON-RPC to include that on the CI checks? 🙏

**Comment by leejw51crypto** [comment]
ok

**Comment by leejw51crypto** [comment]
i cannot reproduce after applying ulimit -n 2000000 option

**Comment by leejw51crypto** [comment]
started
