### ISSUE TITLE
TraceTx/TraceBlock unit test's trace results are different from tx execution

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#767]
__System info:__ ethermint main

Probably not a bug on running code, just an issue with the unit test.

__Steps to reproduce:__
1. Print out the gasUsed in `ApplyMessage` and the traceResult in `TestTraceBlock` unit test, the reported gas usage is different.
2. The difference is traced down to a difference in `SSTORE` opcode gas cost, one is writing a new item and the other one is writing an existing item, thus the difference.
3. It's probably due to wrong context used to call the [`TraceBlock`](https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/grpc_query_test.go#L840) api.

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ 

Don't find a good solution for this.

**Comment by leejw51crypto** [comment]
how about running twice the same tx, to reproduce the same condition?

**Comment by yihuang** [comment]
> how about running twice the same tx, to reproduce the same condition?

The problem is in unit testing, I don't know how to get back the same context when the tx is executed, the context seems not clonable.
