### ISSUE TITLE
Problem: uses too many files open 

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#768]
on ubuntu , default 1024 open file count is not enough.
add some explicit resource management in rpc handlers

**Comment by leejw51crypto** [comment]
checking on this issue

**Comment by odeke-em** [comment]
@leejw51crypto could you please provide more information with say the number of peers, number of seeds, a log of the errors? Thank you.

**Comment by leejw51crypto** [comment]
i used one local server, and send 400 txs concurrently, on and on
errors
"too many open files"

**Comment by leejw51crypto** [comment]
in cr

**Comment by JayT106** [comment]
I think this can be closed!
https://github.com/tharsis/ethermint/pull/773#issuecomment-981234849
