### ISSUE TITLE
`eth_getStorageAt` fails with `"parse error"`

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#77]
__System info:__ 
MacOs

__Steps to reproduce:__

```
// Request
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0x0f54f47bf9b8e317b214ccd6a7c3e38b893cd7f0", "0"  "latest"],"id":1}' -H "Content-Type: application/json" http://localhost:8545
```

__Expected behavior:__ 

```
// Result
{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"}
```
__Actual behavior:__ 
```
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"parse error"}}
```

__Additional info:__ [Include gist of relevant config, logs, etc.]

No log, probably the rpc handler is incorrect

**Comment by crypto-facs** [comment]
When passing a hex param that error is not seen anymore although the endpoint is not working correclty

```--data '{"jsonrpc":"2.0", "method": "eth_getStorageAt", "params": ["0x0680b0c01C2Bf8517EB844BD4Ce47c3f742D25d4", "0x1", "latest"], "id": 1}' \
-H "Content-Type: application/json" \
localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rpc error: code = NotFound desc = rpc error: code = NotFound desc = contract code not found for given address: key not found"}}```

**Comment by fedekunze** [comment]
maybe the account storage gets deleted whenever there's a new `CreateAccount`?

**Comment by crypto-facs** [comment]
Yeah that could be one reason. I also see that the key / index param doesnt seem to be getting into the ABCI query. Saw that while debugging the application as well.

`12:11PM INF ABCIQuery data=0A2A3078383530333230393633656539394541363335626636466237433444333435343130626645653434421242307833363038393461313362613161333231303636376338323834393264623938646361336532303736636333373335613932306133636135303564333832626263 module=rpc path=/ethermint.evm.v1alpha1.Query/Storage result={"code":22,"codespace":"sdk","height":"270","index":"0","info":"","key":null,"log":"rpc error: code = NotFound desc = contract code not found for given address: key not found","proofOps":null,"value":null}
t=2021-07-21T12:11:07+0200 lvl=warn msg="Served eth_getStorageAt"          conn=127.0.0.1:65304 reqid=0                t="386.368µs"              err="rpc error: code = NotFound desc = rpc error: code = NotFound desc = contract code not found for given address: key not found"`

**Comment by thomas-nguy** [comment]
@crypto-facs lets close this issue and open a new one for your issue.

The parse error is just a mistake on my side when copy pasting the doc
