### ISSUE TITLE
Problem: web3 getBlock api could return empty transactions

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#778]
__System info:__ ethermint 0.7.2

__Steps to reproduce:__

We found in production that, `eth_getBlockByNumber` API can return empty transactions occasionally. Which causes issues in explorer and other clients.

Investigation shows that for the problematic block, the tx indexer fails to work at all.
```
$ curl localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270x0e46038e00945639488178aeee4af84f63c6a2229d3c0658e8a8582fb5e63c42%27%22
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "txs": [],
    "total_count": "0"
  }
}
```

And the web3 API tries to call `GetTxsByEthHash` for each tx, and fails to find them.

The tx indexer can also lag behind block commit since it's running async.

__Expected behavior:__ getBlock API should work all the time

__Actual behavior:__ fails occasionally

__Additional info:__

Possible solution:
- don't rely on `GetTxsByEthHash` at all in `eth_getBlockByNumber` and similar apis, we can call `BlockResults` to get the information we need.
- Still need to investigate why tx indexer fails occationally.

**Comment by leejw51crypto** [comment]
does it happen to latest block only?

**Comment by yihuang** [comment]
> does it happen to latest block only?

https://github.com/tendermint/tendermint/issues/7312
it can also happen when tx indexer miss a whole block.

**Comment by JayT106** [comment]
Can we see the log of the node which might have the missing tx indexing?
