### ISSUE TITLE
Problem: reverted contract deployment transaction don't increase sender's nonce

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#808]
__System info:__ ethermint main

__Steps to reproduce:__

1. start a devnet
2. deploy a contract without providing enough gas, it's executed but fails with out-of-gas error
3. sender's nonce is not increased

This means we can have two transactions with the same ethereum tx hash.

__Expected behavior:__ should increase nonce in such case

__Actual behavior:__ nonce not increased

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by leejw51crypto** [comment]
nice catch
