### ISSUE TITLE
The RPC API document seems not updated

### ISSUE THREAD

**Issue by lcmmhcc** [tharsis/ethermint#818]
__Proposal:__ [Description of the feature]

like : https://github.com/tharsis/ethermint/pull/555  seems supported, but not marked in https://docs.ethermint.zone/basics/json_rpc.html
and 
Could u plz export a RPC API Called List ordered by the frequency in one day?

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]
I want to build a RPC node and to learn the RPC API .

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
the docs were migrated to https://evmos.dev/api/json-rpc/server.html, we don't own the ethermint.zone domain unfortunately.

**Comment by lcmmhcc** [comment]
btw, what's the relationship between ethermint and evmos?
