### ISSUE TITLE
websocket error while start the blockchain.

### ISSUE THREAD

**Issue by ppenter** [tharsis/ethermint#82]
__System info:__ 
Ethermint
Ubuntu 20.4 (AWS EC2)

__Steps to reproduce:__

1. git clone https://github.com/tharsis/ethermint
2. cd ethermint/
3. ./init.sh

__Expected behavior:__
No red character error

__Actual behavior:__
![image](https://user-images.githubusercontent.com/55227490/121032133-e83eef00-c7a2-11eb-9620-181f95bf7abe.png)

__Additional info:__

**Comment by JayT106** [comment]
works in macOS with https://github.com/tharsis/ethermint/commit/74b7eaf431a5dcc93f4a592a6aa98befd3c3cb75

**Comment by JayT106** [comment]
tested in Ubuntu 20.04.2 LTS (AWS node) with 9b9c835266408d434b4ff9eea231f80697600bc3. Cannot see the error.

**Comment by fedekunze** [comment]
Please reopen if you see this error again
