### ISSUE TITLE
ethersjs compatibility

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#85]
Check ethersjs compatibility. See https://github.com/cosmos/ethermint/issues/349

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
i'll write testcoding using ether.js try this
1. send amount
2. check it's working good

**Comment by leejw51crypto** [comment]
send amount working good
trying run solidity

**Comment by fedekunze** [comment]
awesome, can you open a PR with the tests?

**Comment by leejw51crypto** [comment]
ok

**Comment by fedekunze** [comment]
@leejw51crypto is this implemented? should we close it now?
