### ISSUE TITLE
EVM profiling

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#86]
Goal: identify bottlenecks and performance improvements

Action items: 

Profile evm module

Document findings

SDK applications expose a profiling address by default that can be used with the [pprof](https://golang.org/pkg/net/http/pprof) library

This can be changed on the config.toml file
- Default address: localhost:6060
- Enable by default and set that address into staport's config.yml  at the root folder of the repo

**Comment by fedekunze** [comment]
@yijiasu-crypto this could be a good task to work on in order to maximize performance of the EVM

**Comment by davcrypto** [comment]
May be can assigned this to me first. Can help on this in coming week. @fedekunze

**Comment by davcrypto** [comment]
@fedekunze pprof server already running by default as "localhost:6060" on Tendermint implementation

Flag: `rpc.pprof_laddr`

```
config.toml

# pprof listen address (https://golang.org/pkg/net/http/pprof)
pprof_laddr = "localhost:6060"
```

**Comment by davcrypto** [comment]
@fedekunze should we close this issue? or is there any other purpose to keep this?
