### ISSUE TITLE
go-ethereum logs are not guarded by log level

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#862]
__Proposal:__ guard go-ethereum logs with loglevel

__Current behavior:__ there are go-ethereum RPC access logs regardless of current log level.

__Desired behavior:__ should be guarded by log level, like `INFO`.

__Use case:__ fewer logs for RPC node.

**Comment by nebkas** [comment]
Finally I found a work around:

In /etc/systemd/system/cronosd.service

add under [service]
LogLevelMax=2
