### ISSUE TITLE
JSON-RPC test framework

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#88]
There are existing tests on  tests/rpcthat need to be updated and fixed

Currently uses a script but we should come up with something more robust

- Check which endpoints are currently failing and create tickets to fix them
- Update documentation currently located on docs/basics/json_rpc.md
- https://github.com/testcontainers/testcontainers-go for Docker tests (?)
- There's also localnet setup using Docker compose that we could use

**Comment by calvinaco** [comment]
Hello @fedekunze , I am working on smoe manual test on RPCs this weekend and come across this issue. Maybe I can give a hand on this issue by converting some of my manual test to automated one.

May I know how's this issue going and anything I could potentially help?
