### ISSUE TITLE
Problem: don't support tx batch sending

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#896]
__Proposal:__ don't support tx batch sending

__Current behavior:__

The client wants to send multiple transactions concurrently and expects them to be included in the block successfully eventually.
The problem is checkTx reject immediately if the nonce check failed, so if transactions from the same sender with increasing nonce arrived at the node in the wrong order, they'll be rejected.
To support this we can either:
- wait for abci++ to support sth similar to go-ethereum's non-executable transaction queue in tendermint
- support multiple `MsgEthereumTx` in the same tx.

In option 2 we need to be able to query eth transaction information by eth tx hash, currently we do that with `/tx_search?query="ethereum_tx.ethereumTxHash=$ETH_TX_HASH"`, in batch tx case, we need to further iterate the result list to find the msg result, should be doable though.

__Desired behavior:__ support multiple `MsgEthereumTx` in the same tx.

__Use case:__ client send batch transactions

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
I think we can support multiple `MsgEthereumTx` (option 2) in the same tx now. We should check that the nonces are increasing (+1) too

**Comment by fedekunze** [comment]
@yihuang if you are planning to work on this maybe we can add it to v.10

**Comment by yihuang** [comment]
> @yihuang if you are planning to work on this maybe we can add it to `v0.10`

yes, I'm working on this one.
