### ISSUE TITLE
Problem: eth batch tx is not tested

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#903]
__Proposal:__ add tests for eth batch tx feature

__Current behavior:__ it's verified manually and in cronos integration test, but not in ethermint repo.

__Desired behavior:__ good to add integration test in ethermint repo too.

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
we should also add unit tests to the RPC util functions that were introduced in your PR
