### ISSUE TITLE
Problem: eth_resend API don't work 

### ISSUE THREAD

**Issue by yihuang** [tharsis/ethermint#905]
__System info:__ ethermint main

__Steps to reproduce:__

Currently, the `eth_resend` simply update the eth tx and broadcast it again, it won't work since we don't have prioritization yet.
Also in the context of multiple eth msgs in one cosmos tx, how can we make it work?

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
we can add mark it as not-supported
