### ISSUE TITLE
How to integrate Ethermint into a Cosmos blockchain made with starport

### ISSUE THREAD

**Issue by WyattMufson** [tharsis/ethermint#930]
How would you add Ethermint as a dependency to a Cosmos SDK blockchain made with starport?

**Comment by fedekunze** [comment]
Hi @WyattMufson, thanks for your interest! 
Unfortunately, this is something that the starport team should integrate into their scaffolding tool themselves so you'd need to add the evm module manually. Happy to answer other questions and feel to reach out to us via the Evmos Discord at any time

**Comment by WyattMufson** [comment]
@fedekunze can you explain how to integrate it manually? I figured it wasn't available out of the box via starport. But I was hoping that there would be an explanation for how to use Ethermint.

Crypto.com's [Cronos](https://github.com/crypto-org-chain/cronos) blockchain is using Ethermint for their EVM support. Looking at their code I see that they have ethermint as a dependency listed in their `go.mod`. And have a `third_party/proto/ethermint` directory and neither an `x/evm` nor `x/ethermint` directory. It looks like the cronos `third_party/proto` is the same as the one in this repo + the contents of the `proto` directory.   

Is there a way to list it as a dependency in go.mod and have it added? Do I need to manually copy in code from this repo? Which files and where do I put them?

If I copy code from this repo is there a way to keep it updated when changes are made here (that's what it looks like Cronos is doing via the `go.mod`)?

**Comment by WyattMufson** [comment]
@fedekunze should I open a new issue for this?

**Comment by tiagommferreira** [comment]
@WyattMufson have you figured this out? I'm in the same situation
