### ISSUE TITLE
ethermintd testnet start has address error

### ISSUE THREAD

**Issue by itsdevbear** [tharsis/ethermint#936]
Note*: When using `-v 1` the network comes up just fine.

(base) devbear@5950x-ubuntu:~/ethermint$ ethermintd testnet init-files
Successfully initialized 4 node directories
(base) devbear@5950x-ubuntu:~/ethermint$ ethermintd testnet start
acquiring test network lock
preparing test network with chain-id "ethermint_1058266398989-1"

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++     THIS MNEMONIC IS FOR TESTING PURPOSES ONLY      ++
++              DO NOT USE IN PRODUCTION               ++
++                                                     ++
++  ribbon good stem uniform wrong cushion exile grid  ++
++   hint beef pulse guard barrel share parent hello   ++
++  half come survey immune hidden survey anger army   ++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

starting test network...
Error: listen tcp 0.0.0.0:8545: bind: address already in use
Usage:
  ethermintd testnet start [flags]

**Comment by poiug07vsys** [comment]
Same issue no Mac OS 12.2.1. Tried both latest release and latest commit from repository.
