### ISSUE TITLE
Decoding MsgEthereumTx in javascript?

### ISSUE THREAD

**Issue by Undead8** [tharsis/ethermint#952]
I need to decode transactions of type `'/ethermint.evm.v1.MsgEthereumTx'` with javascript.

I have been using [cosmjs](https://github.com/cosmos/cosmjs/) to decode the transaction itself, but in order to decode the messages I must use a registry for this specific type. Cosmjs provides a lot of standard types, but none to decode `MsgEthereumTx`. I have been directed to the ethermint team for this issue (see [issue 1060](https://github.com/cosmos/cosmjs/issues/1060#issue-1147120143)).

Is there a way to decode transactions in javascript? Or are you able to provide a registry as mentioned in issue above? Any help would be greatly appreciated. Thanks!

**Comment by fedekunze** [comment]
Hey @Undead8, feel free to use https://github.com/tharsis/evmosjs to decode the txs 👍

**Comment by Undead8** [comment]
@fedekunze Thanks for pointing that out. I checked the repo and I am not sure what to use. Basically, I have a transaction that looks like this "CroICoYICh8vZXRoZXJtaW50LmV2bS52..." (it's a transaction on cronos which uses ethermint) and I need to decode it into an evm format. Could you point me how to use evmosjs to do this? The doc does not seem to cover that.

**Comment by hanchon** [comment]
This PR on evmosjs added that feature https://github.com/tharsis/evmosjs/pull/18 , example on the test file: https://github.com/tharsis/evmosjs/blob/main/packages/proto/src/messages/msgEthereumTx.spec.ts
