### ISSUE TITLE
Metamask keeps failing sending transactions

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#967]
The problem comes from the feemarket base fee.

Metamask does not add any buffer and uses the base fee specified in the block.

Since the average block time is quite fast (few sec), the base fee might increase when it tries to execute it, it fails the transaction.

Solution: Either reintroduce a configurable tip or add a buffer in rpc gas-price endpoints (maybe add 2~5 times the maximum base fee variation)

**Comment by yihuang** [comment]
```
baseFeeDelta = parentBaseFee * (parentGasUsed - parentGasTarget) / parentGasTarget / baseFeeChangeDenominator
```

To get a maximum of baseFeeDelta, we set:

```
parentGasTarget = gasLimit / ElasticityMultiplier
parentGasUsed = gasLimit
```

Then:

```
baseFeeDelta = parentBaseFee * (ElasticityMultiplier - 1) / baseFeeChangeDenominator
```

**Comment by yihuang** [comment]
I think maybe that's too much, after all, user will need to pay those tip fees, so I suggest `baseFee / 8` should be enough to cover most of cases

**Comment by thomas-nguy** [comment]
hmmm `basefee/8` might be too much? its more than 10% more expensive.

I still think that using `baseFeeDelta` might be better. Since the delta change happens every few seconds it should be minimum

**Comment by yihuang** [comment]
> hmmm `basefee/8` might be too much? its more than 10% more expensive.
> 
> I still think that using `baseFeeDelta` might be better. Since the delta change happens every few seconds it should be less

```
baseFeeDelta = parentBaseFee * (ElasticityMultiplier - 1) / baseFeeChangeDenominator
```

assume `ElasticityMultiplier` is default value `2`, the max delta will be `1/8` base fee for one block.
Maybe better to change the `8` to the configured denominator, rather than constant.

**Comment by yihuang** [comment]
I think in ethereum if gas price is not enough, it'll be kept in a future list rather than rejected immediately, which provides much better UX than us, I guess that's possible in the future with abci++.
