### ISSUE TITLE
Refactor `StaticCall`

### ISSUE THREAD

**Issue by fedekunze** [tharsis/ethermint#97]
Refactor StaticCall

EIP: https://eips.ethereum.org/EIPS/eip-214

**Comment by fedekunze** [comment]
@yihuang @thomas-nguy this implementation should be pretty much same as #236

**Comment by yihuang** [comment]
I'm not sure I get the purpose of this issue, the `StaticCall` seems like implementation detail of evm itself? What's the purpose of the query api?
