### ISSUE TITLE
Investigate Upgrading to Tendermint 0.35.2

### ISSUE THREAD

**Issue by itsdevbear** [tharsis/ethermint#992]
Might make sense to wait for 0.36 though. 

Thoughts?

**Comment by fedekunze** [comment]
unfortunately we need for the SDK and ibc-go to bump the Tendermint version first :/

**Comment by itsdevbear** [comment]
SDK is on 0.35.2: [github.com/tendermint/tendermint v0.35.2](https://github.com/cosmos/cosmos-sdk/blob/18635761d5a5ec0becf0941933c511efbf91de77/go.mod#L52)

I did forget about ibc-go though: https://github.com/cosmos/cosmos-sdk/blob/18635761d5a5ec0becf0941933c511efbf91de77/go.mod#L52

**Comment by fedekunze** [comment]
on their latest version they are on `https://github.com/tendermint/tendermint v0.34.14`. I'll close this issue until the next major release
