### ISSUE TITLE
Investigate creating something similar to Minigeth

### ISSUE THREAD

**Issue by itsdevbear** [tharsis/ethermint#993]
Optimism's recent release of minigeth got me thinking that we could do something similar for ethermint. Minigeth is missing important RPC infrastructure, but we could replace that RPC infrastructure with a leaner cosmos/ethermint specific route.

https://github.com/ethereum-optimism/cannon/tree/master/minigeth

**Comment by yihuang** [comment]
what's the main difference with the "full" geth?
